### PR TITLE
Update reflected-xss.yaml

### PR DESCRIPTION
**Pull request by Ahsraeisi**
### Template / PR Information

Added path-based XSS

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @Ahsraeisi !

**Comment by Ahsraeisi** [comment]
@DhiyaneshGeek 
@GeorginaReeder
@ritikchaddha

**Comment by DhiyaneshGeek** [comment]
Hi @Ahsraeisi 

me and @ritikchaddha tried to run this template, we were facing this below error message

image

are you able to run the template successfully ?

**Comment by Ahsraeisi** [comment]
You should put "/" at the end of the input URL.
`nuclei -u https://example.com/ -t test.yaml -dast -vv`

**Review by ritikchaddha — APPROVED** [review]

**Pull request merged**
