### PR TITLE
Pantheon.io subdomain takeover

### PR DESCRIPTION
**Pull request by Pxmme**
image

### CODE REVIEW

**Comment by bauthard** [comment]
Hi @Pxmme, 

Thank you for the PR, this looks good and valid, in the coming days when we have multiple templates for takeovers in the future we can bundle them once as now nuclei support multiple matters for a single request  https://github.com/projectdiscovery/nuclei/pull/32. this allows us to match all the patterns in a single request instead of making 10 requests with 10 templates.

**Comment by Pxmme** [comment]
Hey @bauthard,

Thanks, didn't notice we could check for multiple matters in a single request. I'm looking to implement it and then doing another PR but unfortunately, I'm having a lil bit of troubles doing so:

```yaml
    matchers:
      - type: word
        name: pantheon.io
        words:
          - "The gods are wise, but do not know of the site which you seek."
      - type: regex
        name: worksites
        regex:
          - "(?:Company Not Found|you&rsquo;re looking for doesn&rsquo;t exist)"
        part: body
      - type: word
        name: servfail-hosts
        words:
          - "SERVFAIL"
          - "REFUSED"
```

Returns nothing, and I'm running it against the host with the vulnerable Pantheon.io sub tko. Am I doing something wrong? Is there a line to add to tell the tool that we're looking for multiple stuff in a single request? I didn't find anything regarding that on the [guide](https://github.com/projectdiscovery/nuclei-templates/blob/master/GUIDE.md#multiple-matchers).

By the way, removing the additional matchers and only leaving this one makes it work again:

```yaml
    matchers:
      - type: word
        name: pantheon.io
        words:
          - "The gods are wise, but do not know of the site which you seek."
```

Thanks in advance :)

**Comment by Pxmme** [comment]
Hi @bauthard,

> now nuclei support multiple matters

How can I get the latest version that does that? Tried installing from source but I am still unable to use multiple matchers :(

Thanks!

**Comment by bauthard** [comment]
Hi @Pxmme, 

Here is working example works with the latest version https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/reverse-proxy-detect.yaml

**Comment by noraj** [comment]
Hi @bauthard 

I think what @Pxmme was trying to say is it seems that `go get` will fetech (by default) the last git tag available (here v1.1.0), but at this time it was not working:

```
$ GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei
go: downloading github.com/projectdiscovery/nuclei v1.1.0
go: found github.com/projectdiscovery/nuclei/cmd/nuclei in github.com/projectdiscovery/nuclei v1.1.0
go: downloading github.com/projectdiscovery/gologger v1.0.0
go: downloading gopkg.in/yaml.v2 v2.2.8
go: downloading github.com/logrusorgru/aurora v0.0.0-20200102142835-e9ef32dff381
go: downloading github.com/valyala/fasttemplate v1.1.0
go: downloading github.com/projectdiscovery/retryablehttp-go v1.0.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: github.com/projectdiscovery/retryablehttp-go upgrade => v1.0.1
go: gopkg.in/yaml.v2 upgrade => v2.2.8
go: downloading github.com/projectdiscovery/retryablehttp-go v1.0.1
github.com/logrusorgru/aurora
github.com/projectdiscovery/nuclei/pkg/extractors
github.com/projectdiscovery/gologger
github.com/valyala/bytebufferpool
github.com/valyala/fasttemplate
github.com/projectdiscovery/retryablehttp-go
github.com/projectdiscovery/nuclei/pkg/matchers
gopkg.in/yaml.v2
github.com/projectdiscovery/nuclei/pkg/requests
github.com/projectdiscovery/nuclei/pkg/templates
github.com/projectdiscovery/nuclei/internal/runner
github.com/projectdiscovery/nuclei/cmd/nuclei
```

The change that make it works is already in the master branch but unreleased, so we need to tell `go get` to fetch the last commit of the master branch instead of retrieving the last git tag.

```
GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei@master
go: downloading github.com/projectdiscovery/nuclei v1.1.1-0.20200424191114-5f837610f17b
go: found github.com/projectdiscovery/nuclei/cmd/nuclei in github.com/projectdiscovery/nuclei v1.1.1-0.20200424191114-5f837610f17b
go: downloading github.com/projectdiscovery/retryabledns v1.0.2
go: downloading github.com/miekg/dns v1.1.29
go: downloading github.com/asaskevich/govalidator v0.0.0-20200108200545-475eaeb16496
go: downloading golang.org/x/crypto v0.0.0-20191011191535-87dc89f01550
go: downloading golang.org/x/sys v0.0.0-20190924154521-2837fb4f24fe
go: downloading golang.org/x/net v0.0.0-20190923162816-aa69164e4478
go: golang.org/x/sys upgrade => v0.0.0-20200420163511-1957bb5e6d1f
go: gopkg.in/yaml.v2 upgrade => v2.2.8
go: golang.org/x/net upgrade => v0.0.0-20200421231249-e086a090c8fd
go: golang.org/x/crypto upgrade => v0.0.0-20200423211502-4bdfaf469ed5
go: downloading golang.org/x/net v0.0.0-20200421231249-e086a090c8fd
go: downloading golang.org/x/crypto v0.0.0-20200423211502-4bdfaf469ed5
go: downloading golang.org/x/sys v0.0.0-20200420163511-1957bb5e6d1f
golang.org/x/net/internal/iana
github.com/projectdiscovery/nuclei/pkg/extractors
github.com/asaskevich/govalidator
golang.org/x/crypto/ed25519
golang.org/x/net/bpf
golang.org/x/sys/unix
golang.org/x/net/internal/socket
golang.org/x/net/ipv4
golang.org/x/net/ipv6
github.com/miekg/dns
github.com/projectdiscovery/nuclei/pkg/matchers
github.com/projectdiscovery/retryabledns
github.com/projectdiscovery/nuclei/pkg/requests
github.com/projectdiscovery/nuclei/pkg/templates
github.com/projectdiscovery/nuclei/internal/runner
github.com/projectdiscovery/nuclei/cmd/nuclei
```

**Comment by bauthard** [comment]
Thank you @noraj for pointing this out, we are making few changes before making a new release. 

@Pxmme, for now, can you use the above command to use the latest version.

**Comment by Pxmme** [comment]
Hey @noraj and @bauthard,

Thanks, it worked for me using ``GO111MODULE=on go get -u -v github.com/projectdiscovery/nuclei/cmd/nuclei@master``!

**Pull request merged**
