### PR TITLE
Update php-debugbar-exposure.yaml

### PR DESCRIPTION
**Pull request by geeknik**
### Template / PR Information

- Obliterating false negatives.

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

Odin, bearer of wisdom, see this humble change.
May the lines of my work be etched in Yggdrasil’s bark,
Clear as runes, unbroken, without fear or flaw.
Guide my fingers, that each commit may weave fate
Into a future our kin can honor,
As we do our part in the forging of code.
Skål!

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Beautiful, poetic :D thanks so much as always for your contribution @geeknik !

**Comment by geeknik** [comment]
Thank you @GeorginaReeder, I always appreciate your kind words. 🫶🏻
Now we should chat about your automation classifying this as a weak matcher haha. 🙄
I tested this new version on multiple hosts that the old version missed. This one is better, pinky promise. 🤙🏻

**Comment by DhiyaneshGeek** [comment]
Hi @geeknik 

i have updated the dsl format to refrain from false positive

Let me know if these changes looks good , thanks

**Comment by geeknik** [comment]
LGTM! 

> Let me know if these changes looks good , thanks

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
