### PR TITLE
Update twitter-secret.yaml

### PR DESCRIPTION
**Pull request by daffainfo**
Fixing issue #2229 

Reference: https://github.com/odomojuli/RegExAPI

### CODE REVIEW

**Comment by ehsandeep** [comment]
@daffainfo we have two types for twitter tokens, this update seems to be related to **access tokens**, and existing template checks for **secret tokens** I assume.

Reference:- https://developer.twitter.com/en/docs/twitter-api/getting-started/getting-access-to-the-twitter-api#:~:text=API%20Key%20Secret%20%2D%20This%20is,behalf%20of%20that%20Twitter%20account.

**Comment by daffainfo** [comment]
Sorry, wrong regex

Reference: https://github.com/l4yton/RegHex#twitter-client-id

**Comment by daffainfo** [comment]
@ehsandeep There is twitter oauth and twitter secret, so we can add 2 new template

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
Merged here - https://github.com/projectdiscovery/nuclei-templates/pull/3976

**Pull request closed without merging**
