### PR TITLE
Added Template to detect Exposed Instances of RLOS Cabinet Management…

### PR DESCRIPTION
**Pull request by NoelV11**
… Panel

### Template / PR Information

Description: Retail Loan Origination Systems,developed by NewGen Software is used to streamline consumer loan origination from banking institutions, with end-to-end automation of loan requests in a paperless environment. A Cabinet Panel is used by an RLOS Service to manage storage volumes, that in turn store documents, containing customer PII submitted through the webapp. The RLOS Web Application is deployed on a special service subdomain on of the client's domain infrastructure - with the suffix “rlos" (for example - rlos.company_domain.com) . The path to the Cabinet Storage is omniapp/pages/cabinet/managecabinet.jsf?Action=1. If exposed, it gives an attacker insight into information such as Storage Volume Name, Cabinet Name, it's alias, Deployed AppServer IP Address and Port

Impact:  An attacker can deploy foreign application server instances on the panel using breached credentials for the subdomain, access information about the volume storage and escalate the misconfiguration, by de-registering existing storage systems, so as to route all documents submitted through the platform on an adversary-controlled application server, potentially leading to further compromise.
- References:

### Template Validation

I've validated this template locally?
- [x ] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @NoelV11 

Can you share some link or reference to this ?

Thanks

**Comment by NoelV11** [comment]
Good evening Dhiyaneshwaran,

If i may ask, do you require the link to a vulnerable instance to test this, or for the RLOS System software documentation in general? As far as i have seen, there have been no mentions of this being detected previously

Thank you

**Comment by NoelV11** [comment]
Good evening @DhiyaneshGeek  ,

If i may ask, do you require the link to a vulnerable instance to test this, or for the RLOS System software documentation in general? As far as i have seen, there have been no mentions of this being detected previously

https://www.edms-consultants.com/newgen-rlos/

Thank you

**Comment by NoelV11** [comment]
Good evening @DhiyaneshGeek ,

Adding this Google Dork for reference : inurl:/omniapp/pages/

This template supports detection for RLOS instances, that are exposed and having the address - rlos.company_domain.com

**Comment by NoelV11** [comment]
Good evening @DhiyaneshGeek,

Wanted to make a small clarification, this template supports detection of exposed panel for any host and does not rely on specific subdomain address.

**Comment by NoelV11** [comment]
Good evening @DhiyaneshGeek 

Can i add a comment on the original template, mentioning the dork?

Is it possible

**Comment by DhiyaneshGeek** [comment]
Hi @NoelV11 

let's keep this template as it is  and feel free to send us a another PR for panel detection

Thanks

**Comment by NoelV11** [comment]
Thank you @DhiyaneshGeek , we can go ahead with this template and make it available publicly. Thank you for spearheading and maintaining such an awesome initiative 💯

**Review by ritikchaddha — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
HI @NoelV11 

Thank you so much for sharing this template with the community and contributing to this project 🍻

You can grab some cool PD stickers over here http://nux.gg/stickers 😄

**Pull request merged**
