### PR TITLE
Add Akamai Bot Manager detection

### PR DESCRIPTION
**Pull request by fazlearefin**
### Template / PR Information

- Added Akamai Bot Manager Detection
- References: https://techdocs.akamai.com/identity-cloud/docs/hosted-login-cookies-and-local-storage-1

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @fazlearefin , we appreciate it!

**Comment by mastercho** [comment]
Well thats already here https://github.com/projectdiscovery/nuclei-templates/blob/5ba4166151a0c56fc5cfb16bc3c79be43600256a/http/fuzzing/waf-fuzz.yaml#L386 and PD team tries to not have duplicate templates

**Comment by fazlearefin** [comment]
WAF and Bot Manager are entirely two different Akamai products.

**Comment by mastercho** [comment]
> WAF and Bot Manager are entirely two different Akamai products.

as ex. Akamai worker i can say they both have same ak.bmsc cookie and akamaighost footprint.  And almost same functionality (block page and detection page is same) just bot manager is AI who improve himself by detected attacks

**Comment by fazlearefin** [comment]
That's fine if you are a ex-Akamai worker. The thing to consider is if you have access to the console for testing as these things can change often.

I have access to the current Akamai console. Turning on WAF does not emit any cookie called `ak_bmsc`. So https://github.com/projectdiscovery/nuclei-templates/blob/5ba4166151a0c56fc5cfb16bc3c79be43600256a/http/fuzzing/waf-fuzz.yaml#L390 is most likely outdated.

My PR is to detect whether Bot Manager is turned on in the Akamai console. As Bot Manager can be completely disabled. See also https://www.nokia.com/cookies/cookie-list/

**Review by ritikchaddha — APPROVED** [review]

**Comment by mastercho** [comment]
>  See also https://www.nokia.com/cookies/cookie-list/

Yes as you can see they describe `Helps Akamai distinguish between humans and bots to optimize site security.` which is every WaF functionality just as any others services as Impreva, Securri and etc

**Comment by DhiyaneshGeek** [comment]
Hi @fazlearefin 

Thank you so much for sharing this template with the community and contributing to this project 🍻

You can grab some cool PD stickers over here http://nux.gg/stickers 😄

**Pull request merged**
