### PR TITLE
Added K8S info scan templates

### PR DESCRIPTION
**Pull request by sharathkramadas**
### Template / PR Information

I have added few info severity templates to find out the open ended REST API endpoints in K8S, Kubelet and Etcd components.

### Template Validation

I've validated this template locally?
- YES

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
@sharathkramadas can we have more matcher , status code 200 will give more false positive

**Comment by ehsandeep** [comment]
@sharathkramadas thank you for sharing a template specific to `K8S`, as @DhiyaneshGeek pointed out we need to work on matchers to make sure they are unique for specific endpoints to avoid matchers with random targets responding with 200 status code for any request we make.

**Comment by sharathkramadas** [comment]
Hi @ehsandeep and @DhiyaneshGeek, Thanks! for the suggestions, I will improvise this in few days.

**Comment by sharathkramadas** [comment]
Hi @DhiyaneshGeek  and @ehsandeep i have updated the templates with more matchers.

**Comment by DhiyaneshGeek** [comment]
@sharathkramadas Is there any set-up instruction locally to check these templates ?

**Comment by sharathkramadas** [comment]
If you have vulnerable K8S configured then you can refer this [README](https://github.com/sharathkramadas/k8s-nuclei-templates/blob/main/README.md)

**Comment by DhiyaneshGeek** [comment]
@sharathkramadas thanks for the details and the templates :)

**Comment by raesene** [comment]
in case it's useful, [this repo](https://github.com/raesene/kube_security_lab/) has templates for vulnerable kubernetes clusters that can be setup locally (pre-req's  are Docker , ansible and [kind](https://kind.sigs.k8s.io/docs/user/quick-start/)). there's clusters in there with vulnerable etcd, kubelet and API server.

**Comment by sharathkramadas** [comment]
Thanks for sharing the repo @raesene, Really useful for setting up vulnerable cluster.

**Review by ehsandeep — COMMENTED** [review]
@sharathkramadas Can you please review the severity of each template and update if required? currently, all are `info`.

**Comment by sharathkramadas** [comment]
Hi @ehsandeep, The severities are all INFO only for now as most of them are just information disclosure vulnerabilities.

**Comment by princechaddha** [comment]
Hello @sharathkramadas, thank you so much for sharing these templates with the community and contributing to this project  🚀
We have merged these templates in this PR [here](https://github.com/projectdiscovery/nuclei-templates/pull/4010)

**Pull request closed without merging**
