### PR TITLE
Enabled HTTP Method

### PR DESCRIPTION
**Pull request by skar4444**
Detect enabled HTTP method(PUT,DELETE) on web server

### CODE REVIEW

**Comment by gy741** [comment]
Hello, @skar4444 

It looks like a duplicate template.

What do you think?

https://github.com/projectdiscovery/nuclei-templates/blob/master/miscellaneous/detect-options-method.yaml

**Comment by skar4444** [comment]
Hi @gy741 

The intention is same but I was trying to detect more specific results. Nowadays 99% of servers enable options methods and that gives you all enabled method but this template is more specific to find highly sensitive results.

**Comment by geeknik** [comment]
Duplicate of misconfiguration/put-method-enabled.yaml as well. 👍🏻

**Comment by skar4444** [comment]
Duplicate

**Pull request closed without merging**
