### PR TITLE
gitlab, github & discord file templates

### PR DESCRIPTION
**Pull request by geeknik**
### Template / PR Information

- creates file templates for gitlab and github recovery codes & discord backup codes

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### CODE REVIEW

**Comment by savushkin-yauheni** [comment]
Hi!

What about a lot of false positives ? I think extractors are too common and will spam output. 

Maybe some other fingerprints exists ?

Thanks!

**Comment by geeknik** [comment]
> What about a lot of false positives ? I think extractors are too common and will spam output.

I changed the regex in the Github check. Should cut down on 99% of the false positives now. I just tested it locally and it only found the test file I setup containing a fake backup code. Let me know what you think.

**Comment by savushkin-yauheni** [comment]
Hi again. 

Github looks fine!

But what about others ? They definitely will produce false positives.

**Review by princechaddha — APPROVED** [review]

**Comment by princechaddha** [comment]
Hello @geeknik, thank you so much for sharing these templates with the community and contributing to the project 🍻

The discord and GitLab template were causing a lot of false positives so I have removed them. Feel free to create another PR with an updated regex.

**Pull request merged**
