### PR TITLE
vrealize-hyperic-login-panel

### PR DESCRIPTION
**Pull request by dcruzec**
submitting a pull request for vrealize hyperic login panel.

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @dcruzec , we appreciate it!

**Comment by dcruzec** [comment]
I was trying to add another pull request for [osnexus-quantastor-management-console], did this one get mixed in with my first pull vrealize hyperic login panel

**Comment by dcruzec** [comment]
@DhiyaneshGeek @GeorginaReeder Just checking in on this, please let me know when you get a chance

**Comment by ritikchaddha** [comment]
Hello @dcruzec, thank you so much for sharing this template with the community and contributing to this project 🍻

**Review by DhiyaneshGeek — APPROVED** [review]

**Pull request merged**
