### PR TITLE
generic-db: Check for publicly accessible SQLite database files

### PR DESCRIPTION
**Pull request by Michal-Mikolas**
### Template / PR Information

- This is collection of some web frameworks recommendation or default configuration for SQLite database file location. If this file is publicly accessible due to server misconfiguration, it could result in application data leak including users sensitive data, password hashes etc.
- References:
    - https://laravel.com/docs/11.x/database#sqlite-configuration  (database/database.sqlite)
    - https://laravel.com/docs/5.2/database  (database/database.sqlite)
    - https://github.com/laracasts/larabook/blob/master/app/config/database.php#L51  (app/database/production.sqlite)
    - https://forum.codeigniter.com/post-389846.html  (writable/db.sqlite3)
    - https://github.com/codeigniter4projects/playground/blob/develop/.env.example#L33  (writable/database.db)
    - https://symfony.com/doc/current/doctrine.html#configuring-the-database  (var/app.db)
    - https://symfony.com/doc/4.x/doctrine.html#configuring-the-database  (var/app.db)
    - https://symfony.com/doc/3.x/doctrine.html  (app/sqlite.db)
    - https://symfony.com/doc/2.x/doctrine.html  (sqlite.db)
    - https://openclassrooms.com/forum/sujet/symfony3-sqlite-could-not-create-database  (var/data/db.sqlite)
    - https://symfony.com/doc/current/reference/configuration/doctrine.html#doctrine-dbal-configuration  (var/data/data.sqlite)
    - https://stackoverflow.com/questions/31762878/sqlite-3-database-with-django  (db.sqlite3)
    - https://medium.com/@codewithbushra/using-sqlite-as-a-database-backend-in-django-projects-code-with-bushra-d23e3100686e  (db.sqlite3)
    - https://gist.github.com/jwo/4512764?permalink_comment_id=2235763#gistcomment-2235763  (db/production.sqlite3)
    - https://stackoverflow.com/a/30345819/1632572  (db/production.sqlite3)
    - https://developerhowto.com/2018/12/29/build-a-rest-api-with-node-js-and-express-js/  (db.sqlite)
    - https://sqldocs.org/sqlite/sqlite-nodejs/  (mydb.sqlite)
    - https://stackoverflow.com/questions/41620788/error-database-connection-sqlite-is-missing-or-could-not-be-created-cakephp  (app/data/app_db.sqlite)
    - https://stackoverflow.com/questions/2722383/using-sqlite3-with-cakephp  (app/webroot/database.sqlite, app/database.sqlite)
    - https://levelup.gitconnected.com/how-to-connect-and-use-the-sqlite-database-in-codeigniter-3-48cd50d3e78d  (application/databases/db.sqlite)
    - https://turmanauli.medium.com/how-to-connect-codeigniter-to-sqlite3-database-like-a-pro-2177497a6d30  (application/db/database.sqlite)
    - https://forum.codeigniter.com/thread-74522.html  (application/Database/db1.db)
    - https://stackoverflow.com/a/37088960/1632572  (application/database/data.db)
    - https://docs.laminas.dev/tutorials/getting-started/database-and-models/  (data/*.db)
    - https://phalcon-nucleon.github.io/#!database/getting-started.html  (storage/database/database.sqlite)
    - https://www.yiiframework.com/doc/blog/1.1/en/prototype.database  (protected/data/*.db)
    - https://pusher.com/tutorials/rest-api-slim-part-1/  (db/database.db)
    - https://www.digitalocean.com/community/tutorials/how-to-use-the-fat-free-php-framework  (db/database.sqlite)
    - https://doc.nette.org/en/database/configuration#toc-single-connection  (app/Model/*.db)

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks so much for contributing @Michal-Mikolas !

**Comment by ritikchaddha** [comment]
Hello, @Michal-Mikolas. Thank you for sharing this template with us. However, the matcher added to the template is quite insufficient and weak and will cause numerous false positive results. It would be helpful if you could update the template to include additional strict matchers.

**Comment by Michal-Mikolas** [comment]
Ok, according to [SQLite docs](https://www.sqlite.org/fileformat.html), an SQLite file always start with `SQLite format ` text. I've also verified this for several SQLite files generated by `sqlite3` tool as well as db files used by classic applications (e.g. Google Chrome uses SQLite files to store user cookies, settings etc.). 

I will update the PR soon.

**Comment by Michal-Mikolas** [comment]
Ok, this is the best I can do I guess :-D 

I tried to create matcher that checks the file **STARTS** with the text `SQLite format`, but couldn't find the proper format in the Nuclei documentation :-(

**Comment by Michal-Mikolas** [comment]
> I tried to create matcher that checks the file **STARTS** with the text `SQLite format`, but couldn't find the proper format in the Nuclei documentation :-(

Thanks to @ehsandeep (https://github.com/projectdiscovery/nuclei-templates/discussions/9375) I was able to match exactly beginning of the document.

**Review by DhiyaneshGeek — APPROVED** [review]

**Pull request merged**
