### PR TITLE
Added Templates for DefectDojo and Yopass

### PR DESCRIPTION
**Pull request by AdamCrosser**
###  PR Information

I've created Nuclei templates to detect the Yopass and DefectDojo applications being exposed to the Internet.

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

N/A

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
@AdamCrosser thanks for sharing the templates , but the severity should be something **info**

Shodan : html:"DefectDojo Logo"

**Comment by AdamCrosser** [comment]
@DhiyaneshGeek - Sounds good . I updated the templates to informational. I don't have a strong preference on the risk ratings.

**Comment by DhiyaneshGeek** [comment]
@AdamCrosser you can also add metadata

Reference [Template](nuclei-templates/exposed-panels/pentaho-panel.yaml)

image

shodan-query: 'html:"DefectDojo Logo"'

shodan-query: 'title:"Yopass"'

for both of your template , if you wish :)

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
@AdamCrosser thank you for sharing the new templates.

**Pull request merged**
