### PR TITLE
Add detection of KEYCLOAK

### PR DESCRIPTION
**Pull request by righettod**
Hello,

This PR add a template in the **exposed-panels** area in order to detect any instance of the [Keycloak](https://www.keycloak.org/) tool.

By the way, it fix/complete the current [template](https://github.com/righettod/nuclei-templates/blob/master/exposed-panels/key-cloak-admin-panel.yaml) that did not detect a Keycloak instance, at least with the last version.

Below is the test performed to validate that the template is functional:

image

image

Thanks a lot in advance 😃

### CODE REVIEW

**Comment by ehsandeep** [comment]
thanks for the update @righettod I've updated the existing template to handle both cases, can you confirm this?

**Comment by righettod** [comment]
Hi @ehsandeep It's OK thank a lot :)

**Comment by righettod** [comment]
I have made a test to finally confirm the version of the template and it's OK:

image

image

Thanks a lot for the update 😃 

This project is really amazing 🥇

**Comment by ehsandeep** [comment]
thanks again for confirming this.

**Pull request merged**
