### PR TITLE
Added mysql native pass bruteforce template

### PR DESCRIPTION
**Pull request by iamthefrogy**

### CODE REVIEW

**Review by iamthefrogy — COMMENTED** [review]
approved

**Comment by ehsandeep** [comment]
@iamthefrogy do we have some reference for native-password is vulnerable to brute-force in general that we can link in this template?

**Review by iamthefrogy — COMMENTED** [review]
good changes.

**Comment by ehsandeep** [comment]
@iamthefrogy if we have supported references can we include them in the template or we can update the severity as info for now.

**Comment by ehsandeep** [comment]
making it info as of now, we can update the template as we add more Information.

**Pull request merged**
