### PR TITLE
add docker daemon exposed via http

### PR DESCRIPTION
**Pull request by Arrnitage**
### Template / PR Information

-  Added docker-daemon-exposed
- References:

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

image

#### Additional Details (leave it blank if not applicable)

The exposed-dockerd.yaml always can't detect vulnerability. So I write a template via http method. 

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @Arrnitage , i have made some minor changes to the template and updated the matcher

Let me know if it looks good 

Thanks

**Comment by Arrnitage** [comment]
> Hi @Arrnitage , i have made some minor changes to the template and updated the matcher
> 
> Let me know if it looks good
> 
> Thanks

 Some docker doesn't have containers. the interface /containers/json will be return a null list, so matche '[]' is necessary.

**Comment by DhiyaneshGeek** [comment]
Hi @Arrnitage , i have added null list along with few additional matcher with or condition

let me know if it works now 😄 

Thanks

**Comment by Arrnitage** [comment]
> Hi @Arrnitage , i have added null list along with few additional matcher with or condition
> 
> let me know if it works now 😄
> 
> Thanks

please remove match '"ImageID":' and '"HostConfig":'. If you worry about false positive, please use this mather
```
    matchers-condition: and
    matchers:
      - type: word
        part: body_1
        words:
          - '"ApiVersion":'
          - '"GitCommit":'
          - '"GoVersion":'
          - '"KernelVersion":'
        condition: and
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body_2, "Id") && contains(body_2, "Names") && contains(body_2, "Image") && contains(body_2, "Command") && contains(body_2, "PrivatePort") && contains(body_2, "PublicPort") || contains(body_2, "[]")'
        condition: and
```
if you don't worry about that, can only use dsl matcher

**Comment by pussycat0x** [comment]
@Arrnitage  Thank you for  your contribution to this project. Your efforts are greatly appreciated. Cheers! 🔥

**Review by pussycat0x — APPROVED** [review]

**Pull request merged**
