### PR TITLE
Adding template for EmpireC2 default api login

### PR DESCRIPTION
**Pull request by clem9669**
### Template / PR Information
Hi 👋 

I have created a template for detecting EmpireC2 api login panel.

```sh
...snip...
[VER] [empireC2-default-login-api] Sent HTTP request to https://localhost:1337/api/admin/login
[empireC2-default-login-api] [http] [high] https://localhost:1337/api/admin/login [user=empireadmin,pass=password123]
```

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### Additional References:

- https://bc-security.gitbook.io/empire-wiki/quickstart/configuration/server
- https://github.com/BC-SECURITY/Empire

### CODE REVIEW

**Comment by clem9669** [comment]
@DhiyaneshGeek Hi, could you verify my PR ? 

Many thanks 😄

**Comment by DhiyaneshGeek** [comment]
Hi @clem9669 could provide me some details, how to set-up the docker setup or vulnerable environment for this

Thanks

**Comment by clem9669** [comment]
Sure, the installation procedure is explained here: https://bc-security.gitbook.io/empire-wiki/quickstart/installation

You have a docker if you want. However, I made my test on the kali install `sudo apt install powershell-empire`

As stated [here](https://bc-security.gitbook.io/empire-wiki/quickstart/configuration/server), the default creds are: 
    username: empireadmin
    password: password123

**Comment by DhiyaneshGeek** [comment]
@clem9669 Thank you for sharing this template with the community and for your contribution to this project.

i have made few changes to the template, let me know if it works :)

**Review by ritikchaddha — APPROVED** [review]

**Pull request merged**
