### PR TITLE
Modified yaml2json script to output valid JSON array

### PR DESCRIPTION
**Pull request by aditya20-b**
**Fixes:**
- Corrected `yaml2json.go` to output as a single, valid JSON array when invoked via CI/CD actions. This resolves parsing issues with the previously invalid JSON format in `cve.json`.

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thank you so much for your contribution @aditya20-b , we appreciate it!

**Comment by ehsandeep** [comment]
@aditya20-b `cves.json` written in json line format, so if you parse them as json lines it should work as expected.

**Comment by aditya20-b** [comment]
Got it @ehsandeep, Just thought standard JSON might make things a bit smoother for tool integration and parsing straight off the bat instead of line parsing

**Comment by ehsandeep** [comment]
NP! closing as it's already possible to parse, changing format is also breaking chane for existing automation.

**Pull request closed without merging**
