### PR TITLE
Regex issues fix by simplifying and fixing some edge cases

### PR DESCRIPTION
**Pull request by Ice3man543**

### CODE REVIEW

**Comment by Pxmme** [comment]
CRLF injection isn't catching edge cases anymore:

image

**Comment by bauthard** [comment]
@Pxmme this is still being worked on, as you noticed in the issue we are missing few valid ones with CRLF and open-redirect templates.

**Comment by Pxmme** [comment]
@bauthard my regexes are broken :'( sorry, I'm a noob lmao

I'll take a look at those cases that are being missed and try to fix it!

Double-space missed too by this PR:

image

**Comment by bauthard** [comment]
no worries, we will get it sorted, thanks for pointing out the above case as well.

**Comment by melbadry9** [comment]
@Ice3man543 I have tested CRLF injection regex and still miss valid ones!!

**Comment by manuelbua** [comment]
Hi, I've seen the missing edge cases and added some checks for both (remove the `(?i)` if case-insensitive is not wanted).

Would you like me to push these to [iceman-regex-fix](/projectdiscovery/nuclei-templates/tree/iceman-regex-fix) for review?

**crlf-injection**
```
regex: (?i)(?:Set-Cookie\:(?:\s*?|.*?;\s*?))(crlfinjection\=crlfinjection)

testcases:
Set-Cookie:  abc=123; crlfinjection=crlfinjection;  test=123
Set-Cookie: abc=123;  crlfinjection=crlfinjection; test=123
Set-Cookie:  crlfinjection=crlfinjection;
Set-Cookie: crlfinjection=crlfinjection;
Set-Cookie: crlfinjection=crlfinjection;
Set-Cookie: abc=123; def=abz; zz=11; crlfinjection=crlfinjection; test=123
Set-Cookie: abc=123; def=abz;  zz=11; crlfinjection=crlfinjection; test=123
Set-Cookie: abc=123; def=abz; zz=11;crlfinjection=crlfinjection; test=123

```

**open-redirect**
```
regex: (?i)(?:Location\:\s*?)(?:https?:\/\/)?(?:[a-zA-Z0-9\-_]*\.)?evil\.com

testcases:
Location: evil.com
Location: sub.evil.com
Location: http://evil.com
Location: https://evil.com
Location: http://sub.evil.com
Location: https://sub.evil.com
Location: http://legit.com/evil.com
Location: https://legit.com/evil.com
Location: legit.com/evil.com
Location: notevil.com
Location:  evil.com

```

@melbadry9 can you test/share your testcases for the CRLF injection one? I can try add some more missing cases.

**Comment by Ice3man543** [comment]
Hey, I've been busy with some other work and hence have been inactive on this pr. Could you push your work In the pr? It would be much appreciated.

**Comment by manuelbua** [comment]
@Ice3man543 looks like i can't really push on this repo, but i can fork it and make another PR and reference this in the new one?

**Comment by melbadry9** [comment]
Hey @manuelbua, 

- CRLF Injection regex is working great. 
- Open Redirect regex is missing a test case

```http
Location: //evil.com
```

**Comment by manuelbua** [comment]
Thank you @melbadry9, updated #152 to handle protocol-relative URLs as well.

**Comment by bauthard** [comment]
Thanks alot @manuelbua @melbadry9 @Pxmme helping on this to improve the detection, going to merge this asap.

**Comment by melbadry9** [comment]
Hey @manuelbua 

- I found that the regex is generating many false positive with the following test case 

```http
Location: https://honeybear-stage.example.com/%0D%0ASet-Cookie:crlfinjection=crlfinjection
```

**Comment by manuelbua** [comment]
Is the regex the crlf-injection one against that test?

**Comment by manuelbua** [comment]
@melbadry9 i switched to using multiline matching in the headers and anchoring to the start-of-text, this should get rid of the false positives, please let me know thanks!

**Pull request merged**
