### PR TITLE
add django variables exposure template

### PR DESCRIPTION
**Pull request by CaledoniaProject**
### Template / PR Information

Reference: https://github.com/projectdiscovery/nuclei/discussions/2409

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

```
# nuclei -itags exposures -u hxxp://64.215.201.234:8081/ -json -ni
```

### CODE REVIEW

**Comment by CaledoniaProject** [comment]
@forgedhallpass Can you take a look at this?

**Comment by forgedhallpass** [comment]
@CaledoniaProject thank you for your contribution!
The template looks quite alright. Some minor things could be improved with regards to the meta-data: 
* description field is missing
* the `django` tag should be added
* maybe a better ID and/or template name could be added
* it would potentially make sense to use the references from the other existing template (referenced below)
* are you sure you want to go with the `author` "nobody" instead of your handle?

One of our triagers will validate the template and then it will be merged. @DhiyaneshGeek has already assigned it to himself.

Related file template:
https://github.com/projectdiscovery/nuclei-templates/blob/master/file/logs/django-framework-exceptions.yaml

**Comment by CaledoniaProject** [comment]
@forgedhallpass All done. Please check again.

**Comment by DhiyaneshGeek** [comment]
@CaledoniaProject Thanks for the template contribution :)

**Review by princechaddha — APPROVED** [review]

**Pull request merged**
