### PR TITLE
truenas core panel

### PR DESCRIPTION
**Pull request by rxerium**
### Template / PR Information

Template to detect truenas core panels

References:
- https://www.truenas.com/docs/scale/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @rxerium i compared the response body of truenas scale and truenas core it doesn't have any difference only the logo of the image is changed

the endpoint and response is same , so we are considering this as duplicate template and closing this PR 

Thanks 😄

**Comment by rxerium** [comment]
Hey @DhiyaneshGeek, I was matching on the below text on the login page:
```
"TrueNAS CORE® © 2023
```
image


Is this still not applicable? Thanks!

**Comment by DhiyaneshGeek** [comment]
Hi @rxerium 

Can you check if those keywords are present in `view-source:`

Looking forward to hear back from you

Thanks

**Comment by rxerium** [comment]
Yes it does exist, while I don't have access to TrueNAS CORE I presume it is the same:
image

**Comment by DhiyaneshGeek** [comment]
Hope you got it

Feel free to re-open the PR if you have more information

Thanks

**Comment by rxerium** [comment]
Will do! I've asked a discord community I'm in and will feedback. Thanks!

**Pull request closed without merging**
