### PR TITLE
Add umami-detect template

### PR DESCRIPTION
**Pull request by userdehghani**
### Template / PR Information

- References: https://umami.is/

### Template Validation

I've validated this template locally?
- [x] YES

### CODE REVIEW

**Comment by userdehghani** [comment]
telegram-cloud-photo-size-4-5875036952351326904-y

this is my burp and I tried to write a template for umami tech detection, but when I tested it using the online nuclei template editor, I could not reach the same result.
Is it possible to check the issue?

**Comment by GeorginaReeder** [comment]
Thanks for your contribution @userdehghani , we really appreciate it!

**Comment by userdehghani** [comment]
can you guide me regarding PR processing cycle? 3/4 days passed and there has been no update on this PR

@GeorginaReeder

**Review by ritikchaddha — APPROVED** [review]

**Comment by ritikchaddha** [comment]
Hello @userdehghani, thank you so much for sharing this template with the community and contributing to this project 🍻

**Pull request merged**
