### PR TITLE
AWS service detection template

### PR DESCRIPTION
**Pull request by 6mile**
### Template / PR Information

This Nuclei template detects 8 AWS services via HTTP headers or HTML body content.   
These services include ALB, Cloudfront, Codebuild, API Gateway, KMS, Xray, WAF and DynamoDB

- References:  
       - https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonRequestHeaders.html

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO
nuclei-aws-detect

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by 6mile** [comment]
heya @ritikchaddha is there an issue with this PR?  I'm working with Project Discovery community team and wondering if you need something from me to get this PR approved and merged?

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @6mile Thank you so much for sharing this template with the community and contributing to this project !

**Comment by ritikchaddha** [comment]
Hello @6mile, Thank you for sharing this template and contributing to the project. I've validated and updated the template and removed a few duplicate header matchers. Could you please confirm that the new template works for you?

**Comment by 6mile** [comment]
Heya @ritikchaddha yup, that works for me.  Thanks!

**Pull request merged**
