### PR TITLE
fix: false postive - metadata service check templates

### PR DESCRIPTION
**Pull request by daffainfo**
Added more matcher to metadata service check templates

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @daffainfo are these changes validated locally ?

**Comment by daffainfo** [comment]
@DhiyaneshGeek i didnt test all of the template but all of them are based from documentation between each services, for example:
- https://docs.digitalocean.com/reference/api/metadata-api/

We found that almost all metadata-* templates have very few matchers (only 1 - 2 words and the value matcher condition is `or` not and lead to false positive result)

**Comment by DhiyaneshGeek** [comment]
Hi @daffainfo 

can you share a FP target over discord (#geekfreak)

Looking forward to see you there

Thanks

**Comment by DhiyaneshGeek** [comment]
Hi @daffainfo 

Is `metadata-google.yaml` is it running it on a GCP host itself ?

if there is something updated on the GCP Metadata documentation, we can review and update the template accordingly 

Looking forward to hear back from you

Thanks

**Comment by ehsandeep** [comment]
Thank you, @daffainfo, for the updates. However, due to the lack of information, let’s hold off on making changes to all other templates for now.

Feel free to update specific templates with additional matchers for which you experienced false positive in separate pull request. Updating others could lead to false negatives, so we should avoid making changes to them unless they are also producing false positives.

**Pull request closed without merging**
