### PR TITLE
Create rdweb-detect.yaml

### PR DESCRIPTION
**Pull request by rxerium**
### Template / PR Information

Nuclei template to detect RD Web panels 

References:
Shodan Query: https://www.shodan.io/search?query=Set-Cookie%3A+TSWAFeatureCheckCookie%3Dtrue%3B+path%3D%2FRDWeb%2F

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @rxerium Thank you so much for sharing this template with the community

**Comment by rxerium** [comment]
Thanks for your reply @princechaddha, in my initial PR  the path was set to `{{BaseURL}}/RDWeb` and it matched on the header as matching on the body would not bring back results in other languages.

**Comment by DhiyaneshGeek** [comment]
Hi @rxerium i have updated the template to `/RDWeb/Pages/en-US/login.aspx?ReturnUrl=/RDWeb/Pages/en-US/Default.aspx` so that it would detect the login panels 

when i tested on the header based `Set-Cookie: TSWAFeatureCheckCookie=true; path=/RDWeb/` instance, it was observed that it was eventually redirecting to the login panel

Let me know if the detection misses any targets ?

Thanks 
DhiyaneshGeek

**Comment by rxerium** [comment]
Hey @DhiyaneshGeek sorry for the delay on this. I found an example of a host in another language which does not redirect to the US english page: `https://rdgw.patentship.eu/RDWeb/Pages/de-DE/login.aspx?ReturnUrl=/RDWeb/Pages/de-DE/Default.aspx`

**Pull request merged**
