### PR TITLE
Add limesurvey detector

### PR DESCRIPTION
**Pull request by Yablargo**
### Template / PR Information

When reviewing domains I am responsible for, I came upon this app:

https://www.limesurvey.org/

Screen Shot 2023-03-06 at 11 56 29 AM

I had never seen anything about this before, but found that there were multiple CVEs:

https://www.cvedetails.com/vulnerability-list/vendor_id-6900/Limesurvey.html (I will try to get some vuln templates going when I understand more)

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by Yablargo** [comment]
Sorry, I have a LOT of results, and apparently this is already covered in the "Generic CMS Detector" so I should probably close this I think. Gonna leave it open a few in case I can get the CVEs working

**Comment by ritikchaddha** [comment]
Hello @Yablargo, this template looks fine to me, I can make the necessary changes in the template for you such as updating the matcher and other things.

**Comment by Yablargo** [comment]
@ritikchaddha I need to modify it a little bit.. I have uh, quite a lot of domains I can poke at, and I got a lot of false positives here, so I need to check for more terms on the landing page, or look for a specific limesurvey-only page.

**Comment by Yablargo** [comment]
Huh, I wonder if this is just because I forgot to add ```matchers-condition: and```  ?

**Comment by Yablargo** [comment]
@ritikchaddha If it's worthwhile, great I'm happy with that, if not I will try to get some of the CVEs working if so, I'll post the appropriate templates when I can get something working!

**Comment by ritikchaddha** [comment]
Hello @Yablargo, Thank you for sharing these templates with the community and for your contribution to this project. Your efforts are greatly appreciated. Cheers!

I've updated the matchers to avoid false negatives; please check and let us know if it works for you!

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @Yablargo Thank you so much for sharing this template with the community !

**Pull request merged**
