### PR TITLE
Add case-insensitive flags to fingerprinthub and tech-detect templates

### PR DESCRIPTION
**Pull request by knavesec**
Add case-insensitive flags to fingerprinthub and tech-detect templates. Goal is to decrease the prevalence of false-negatives where the search string is there, but something changes the exact case. 

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### CODE REVIEW

**Comment by knavesec** [comment]
Looks like the assigned reviewer check failed, so manually assigning a reviewer 
image

**Comment by olearycrew** [comment]
Thanks for this contribution @knavesec

**Comment by knavesec** [comment]
Bumping this again @DhiyaneshGeek and @pussycat0x

**Review by ritikchaddha — APPROVED** [review]

**Comment by ritikchaddha** [comment]
Hello @knavesec, We appreciate your efforts in updating the template and making it more suitable, Your contribution has been truly valuable to us. Cheers! 🍻

**Pull request merged**
