### PR TITLE
redirection-regex-fix

### PR DESCRIPTION
**Pull request by princechaddha**
### Template / PR Information

It was identified that the existing redirection regex in few templates may result in false positives in cases where location header is `Location: example.com`. Therefore we have updated the regex to https://regex101.com/r/xXqb6e/1. 

If you have any feedback or encountered edge cases, please let us know. Thanks

### CODE REVIEW

**Comment by geeknik** [comment]
Your example appears to miss a couple of edge cases such as a lowercase `location` and will miss a redirect such as `Location: example.com` which is missing `http(s)` or `//`. Some servers don’t play by the established rules. Am not at my PC otherwise I’d share an improved regex.

**Comment by geeknik** [comment]
Here is my suggested regex:
`(?mi)(?:Location\s*?:\s*?)((?:https?:\/\/|\/\/?))?(?:[a-zA-Z0-9\-_\.@]*)example\.com.*`

which catches the following:
```
Location: https://example.com
Location: http://example.com
location: http://example.com
Location: //example.com
location: example.com
Location:http://example.com
```

https://regex101.com/r/ihtzrD/1

Am curious if anyone has further suggestions to improve it.

**Comment by osamahamad** [comment]
@geeknik thanks for adding, the provided regex still generate a false positive 

```
Location: example.com.google.com
```
considered valid for ```(?mi)(?:Location\s*?:\s*?)((?:https?:\/\/|\/\/?))?(?:[a-zA-Z0-9\-_\.@]*)example\.com.*``` as mentioned in #2821

**Comment by geeknik** [comment]
Thank you for that. Luckily it is easily fixed by changing my original suggestion to 
`(?mi)^(?:Location\s*?:\s*?)((?:https?:\/\/|\/\/?))?(?:[a-zA-Z0-9\-_\.@]*)example\.com$`

**Comment by ehsandeep** [comment]
@geeknik additionally, we may need to handle the following scenario in which the input target (target.com) is appended, leaving it open to redirection because `comtarget.com` will be considered user controlled.

```
Location:http://example.comtarget.com
```

**Comment by geeknik** [comment]
@ehsandeep I believe that can be fixed by something along the lines of

`(?mi)^(?:Location\s*?:\s*?)((?:https?:\/\/|\/\/?))?(?:[a-zA-Z0-9\-_\.@]*)example\.com|{{hostname}}$`

https://regex101.com/r/2NPf7i/1

**Comment by ehsandeep** [comment]
@geeknik unfortunately global variables are not supported yet in matchers/extractors, we recently added support for it only for `word` matchers in the dev branch.

**Comment by geeknik** [comment]
In that case, I'm not sure how to match on `example.comtarget.com` but not `example.com.target.com`

**Comment by ehsandeep** [comment]
@geeknik the latter can be handled with negative word matcher with next release of nuclei.

```yaml
      - type: word
        negative: true
        part: header
        words:
          - "example.com.{{Host}}"
```

**Comment by ehsandeep** [comment]
this should be closed with https://github.com/projectdiscovery/nuclei-templates/pull/3299

**Pull request closed without merging**
