### PR TITLE
added alive-hosts-checker

### PR DESCRIPTION
**Pull request by bauthard**
Fixes https://github.com/projectdiscovery/nuclei-templates/issues/67

### CODE REVIEW

**Comment by Zeokat** [comment]
I think that the convention is not include http/https into path, because each webpage tested can be different. The shcheme HTTP or HTTPS, should be defined into the input URL list (user defined), not into the template from my point of view.

**Comment by bauthard** [comment]
Hi @Zeokat, 

Thanks for the feedback, here I've used `https://` in the template on purpose, so what this template will do is force the `nuclei` to request all the user-submitted subdomains running with `https`, so this allows us to filter dead host from the subdomain list and get the alive URLs out of it, URLs running on `http` and not `https` is still a concern and need to see how that can be solved, but yeah as of now it's helper template to get all the URLs over https from passive list of subdomains.

**Comment by Zeokat** [comment]
@bauthard but why not follow the same rules of other templates and simply use:

```
requests:
  - method: GET
    path:
      - "{{BaseURL}}"
```

In this way is the user who decide use http or https according to his needs. I can't understand why force https is needed, since is into the input url list where you define http or https.

**Comment by bauthard** [comment]
Hi @Zeokat, 

Agree on that point, will close this out till we figure out about protocol handling.

**Pull request closed without merging**
