### PR TITLE
Add Directus Detect

### PR DESCRIPTION
**Pull request by ricardomaia**
### Template / PR Information

Directus is a content manager with dynamic access API generation and transparent integration with the main databases.

This PR implements a template for identifying Directus instances based on a specific header value.

image

- References:
  - https://directus.io/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @ricardomaia i have made some changes to the template, let me know if it works for you

also i have removed the `redirect` and `stop-at-first-match` , since i'm getting the same level results when used with `-stats` flag

Looking forward to hear back from you

Thanks for contributing to the template project !

**Review by pussycat0x — APPROVED** [review]

**Comment by pussycat0x** [comment]
Hi @ricardomaia  Thank you for your contribution to this project. Your efforts are greatly appreciated. Cheers!

**Comment by ricardomaia** [comment]
> Hi @ricardomaia i have made some changes to the template, let me know if it works for you
> 
> also i have removed the `redirect` and `stop-at-first-match` , since i'm getting the same level results when used with `-stats` flag
> 
> Looking forward to hear back from you
> 
> Thanks for contributing to the template project !

Thanks @DhiyaneshGeek for quickly response . I see no problem with changes, except by google-dork. "X-Powered-By: Directus" search in Google give us a completly an less precise result than intitle:directus "Not Authenticated" and I didn't understand the reason for this change. Could you explain your reasoning to me? This would certainly help me in future contributions.

**Comment by DhiyaneshGeek** [comment]
Hi @ricardomaia "X-Powered-By: Directus” is a Shondan Query , can you try and confirm 

thanks

**Comment by ricardomaia** [comment]
> Hi @ricardomaia "X-Powered-By: Directus” is a Shodan Query , can you try and confirm
> 
> thanks

OK. I confirm that this is the correct query for Shodan, so the metadata key should be changed from `google-dork` to `shodan-query` or keep both, do you agree? 

```yaml
[...]
  metadata:
    max-request: 1
    google-query: intitle:directus "Not Authenticated"
    shodan-query: "X-Powered-By: Directus"
    verified: true
[...]
```

**Comment by DhiyaneshGeek** [comment]
Hi @ricardomaia yes we can use both google-query and shodan-query 

I agree with you :)

**Pull request merged**
