### PR TITLE
added template for xss params

### PR DESCRIPTION
**Pull request by foulenzer**
added a template to search for reflected xss on 15 of the most common vulnerable xss parameter

### CODE REVIEW

**Comment by michael1026** [comment]
Out of curiosity, any reason this is 15 requests instead of just one request with 15 parameters?

**Comment by foulenzer** [comment]
A few less lines with the cost of customizability (is this a word?). I have no numbers, but I guess most of the users do not edit the templates ☺️

**Comment by bauthard** [comment]
Thank you for the PR @foulenzer, curious to know if that payload works for you or it's just for probing? 

image

**Comment by foulenzer** [comment]
Hey @bauthard this payload works for me in many cases, especially when "script" is blocked

**Comment by foulenzer** [comment]
okay, I didn't saw your fiddle. In fiddle it does not work for me too, but I got some "proofs" :-D

https://www.openbugbounty.org/reports/1137761/
https://www.openbugbounty.org/reports/1131296/
https://www.openbugbounty.org/reports/1124146/

it is basically the same payload.

**Comment by dwisiswant0** [comment]
I think it should be put in `basic-detections/basic-xss-prober.yaml`.

**Comment by bauthard** [comment]
Thank you for the PR @foulenzer, I've merged them into one and updated the payload, as we are doing generic checks.

**Pull request merged**
