### PR TITLE
Postgresql detection template

### PR DESCRIPTION
**Pull request by nybble04**
### Template / PR Information

This template detects if a Postgresql RDBMS server is running on the target by looking for postgres-specific authentication responses. 

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

Docker tags used for local testing:
- [postgres:latest](https://hub.docker.com/layers/library/postgres/latest/images/sha256-e6a3a637b159ed477c09dd5415119178496b53f0599c0aa483fb876cd432f9f8?context=explore) , for the new SCRAM-SHA-256 authentication. 
- [postgres:9.4.26-alpine](https://hub.docker.com/layers/library/postgres/9.4.26-alpine/images/sha256-53d26cfae686348620109ee2a0df265e5e58e24cbecff66828c1113edee9b174?context=explore) , for the old MD5 authentication.

### Additional References:
The network data being sent is that of a psql client, captured using the `network-fingerprint` tool as given in the blog below. 
- [PSQL client](https://www.postgresql.org/docs/current/app-psql.html)
- [Writing Network Templates with Nuclei](https://blog.projectdiscovery.io/writing-network-templates-with-nuclei/)

### CODE REVIEW

**Comment by pussycat0x** [comment]
Hi @nybble04  Thank you for sharing this template with the community and for your contribution to this project. we observed this template contains weak matchers. so could you please update the strong matchers? cheers.
Reference debug data below.
```
[INF] [pgsql-detect] Dumped Network request for 127.0.0.1:5432
00000000  00 00 00 50 00 03 00 00  75 73 65 72 00 6e 75 63  |...P....user.nuc|
00000010  6c 65 69 00 64 61 74 61  62 61 73 65 00 6e 75 63  |lei.database.nuc|
00000020  6c 65 69 00 61 70 70 6c  69 63 61 74 69 6f 6e 5f  |lei.application_|
00000030  6e 61 6d 65 00 70 73 71  6c 00 63 6c 69 65 6e 74  |name.psql.client|
00000040  5f 65 6e 63 6f 64 69 6e  67 00 55 54 46 38 00 00  |_encoding.UTF8..|
00000050  70 00 00 00 36 53 43 52  41 4d 2d 53 48 41 2d 32  |p...6SCRAM-SHA-2|
00000060  35 36 00 00 00 00 20 6e  2c 2c 6e 3d 2c 72 3d 00  |56.... n,,n=,r=.|
00000070  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|
00000080  00 00 00 00 00 00 00                              |.......| address=127.0.0.1:5432
[DBG] [pgsql-detect] Dumped Network response for 127.0.0.1:5432

00000000  45 00 00 00 91 53 46 41  54 41 4c 00 43 32 38 30  |E....SFATAL.C280|
00000010  30 30 00 4d 6e 6f 20 70  67 5f 68 62 61 2e 63 6f  |00.Mno pg_hba.co|
00000020  6e 66 20 65 6e 74 72 79  20 66 6f 72 20 68 6f 73  |nf entry for hos|
00000030  74 20 22 31 30 36 2e 31  39 37 2e 38 38 2e 31 33  |t "127.0.0.1|
00000040  30 22 2c 20 75 73 65 72  20 22 6e 75 63 6c 65 69  |0", user "nuclei|
00000050  22 2c 20 64 61 74 61 62  61 73 65 20 22 6e 75 63  |", database "nuc|
00000060  6c 65 69 22 2c 20 53 53  4c 20 6f 66 66 00 46 61  |lei", SSL off.Fa|
00000070  75 74 68 2e 63 00 4c 34  39 32 00 52 43 6c 69 65  |uth.c.L492.RClie|
00000080  6e 74 41 75 74 68 65 6e  74 69 63 61 74 69 6f 6e  |ntAuthentication|
00000090  00 00        
```                                     |..|

**Comment by nybble04** [comment]
Hiya @pussycat0x, 
Sure! I have modified the list with the [postgres authentication error codes](https://www.postgresql.org/docs/current/errcodes-appendix.html) (28000, 28P01) for better matching. I have also added some other expected/common words to the list.

00000000  45 00 00 00 91 53 46 41  54 41 4c 00 43 32 38 30  |E....SFATAL.C**280**|
00000010  30 30 00 4d 6e 6f 20 70  67 5f 68 62 61 2e 63 6f  |**00**.Mno **pg_hba.co**|
00000020  6e 66 20 65 6e 74 72 79  20 66 6f 72 20 68 6f 73  |**nf** entry for hos|
00000030  74 20 22 31 30 36 2e 31  39 37 2e 38 38 2e 31 33  |t "127.0.0.1|
00000040  30 22 2c 20 75 73 65 72  20 22 6e 75 63 6c 65 69  |0", **user "nucle**i|
00000050  22 2c 20 64 61 74 61 62  61 73 65 20 22 6e 75 63  |**", database "nuc**|
00000060  6c 65 69 22 2c 20 53 53  4c 20 6f 66 66 00 46 61  |**lei"**, SSL off.Fa|
00000070  75 74 68 2e 63 00 4c 34  39 32 00 52 43 6c 69 65  |uth.c.L492.RClie|
00000080  6e 74 41 75 74 68 65 6e  74 69 63 61 74 69 6f 6e  |ntAuthentication|
00000090  00 00

00000000  52 00 00 00 0c 00 00 00  05 44 6f f7 74 45 00 00  |R........Do.tE..|
00000010  00 5f 53 46 41 54 41 4c  00 43 32 38 50 30 31 00  |._SFATAL.C**28P01**.|
00000020  4d 70 61 73 73 77 6f 72  64 20 61 75 74 68 65 6e  |Mpassword authen|
00000030  74 69 63 61 74 69 6f 6e  20 66 61 69 6c 65 64 20  |tication failed |
00000040  66 6f 72 20 75 73 65 72  20 22 6e 75 63 6c 65 69  |for **user "nuclei|**
00000050  22 00 46 61 75 74 68 2e  63 00 4c 32 38 36 00 52  |**"**.Fauth.c.L286.R|
00000060  61 75 74 68 5f 66 61 69  6c 65 64 00 00           |auth_failed..|

00000000  52 00 00 00 17 00 00 00  0a 53 43 52 41 4d 2d 53  |R........**SCRAM-S**|
00000010  48 41 2d 32 35 36 00 00                           |**HA-256**..|

**Comment by pussycat0x** [comment]
Hi @nybble04  thanks for adding new macthers.

**Comment by DhiyaneshGeek** [comment]
Hi @nybble04 Thank you for sharing this template with the community and for your contribution to this project.

**Review by DhiyaneshGeek — APPROVED** [review]

**Pull request merged**
