### PR TITLE
implement wordpress-yoast-seo-user-enumeration

### PR DESCRIPTION
**Pull request by FLX-0x00**
### Template / PR Information

This template is capable of detecting and extracting usernames from a special sitemap xml file that is generated on wordpress when using Yoast SEO Plugin and the default settings. You can disable this specific functionality in the plugin settings.

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

image

image

Google Dork
inurl:/author-sitemap.xml "xml"

### CODE REVIEW

**Comment by FLX-0x00** [comment]
@ritikchaddha can you explain me the changes especially the extractors?! Don't think this will extract the author names. Want to learn from that :)

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @FLX-0x00 Thank you so much for sharing this template with the community

**Comment by FLX-0x00** [comment]
@DhiyaneshGeek  can you explain me the changes especially why remove the extractors?!. Want to learn from that :)

**Comment by ritikchaddha** [comment]
Hey @FLX-0x00, Adding the extractor to the template to extract all the usernames is also not a good idea because it causes the CLI result to be unclear, and confusing.

**Comment by FLX-0x00** [comment]
> Hey @FLX-0x00, Adding the extractor to the template to extract all the usernames is also not a good idea because it causes the CLI result to be unclear, and confusing.

thanks for clearing this to me. helps to improve my futher contributions

**Pull request merged**
