### PR TITLE
Created gitlab-enum.yaml

### PR DESCRIPTION
**Pull request by evilgensec**
### Description

This template is designed to identify accessible GitLab instances by checking the availability of two key endpoints: /explore and /api/v4/projects. It performs HTTP GET requests to these endpoints and validates that they return a status code of 200, indicating that the endpoints are operational.

### Template / PR Information

Purpose: This template aids security professionals and penetration testers in discovering live GitLab instances and assessing their accessibility. It ensures that the specified endpoints are reachable, facilitating the initial reconnaissance phase of security assessments.

**`/explore`**: This endpoint typically provides an interface for users to explore available projects within a GitLab instance. If accessible, it can give insight into the projects hosted on the instance, including their visibility settings (public, private, or internal). This can reveal valuable information regarding the organization's activities, team structures, and project collaborations, which can be critical during a security assessment.

**`/api/v4/projects`**: This API endpoint allows users to access detailed information about the projects hosted on the GitLab instance. If this endpoint returns a status code of 200, it may indicate that the API is publicly accessible, which could pose a security risk. Security professionals can leverage this endpoint to gather more data about project configurations, members, and permissions, allowing them to identify potential vulnerabilities or misconfigurations in the GitLab setup.

Contribution: This is a contribution from my side for Hacktoberfest and the ongoing development of Nuclei. By adding this template, I aim to enhance the community's ability to perform security assessments effectively on GitLab instances.

Template_Validated_Locally

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### CODE REVIEW

**Comment by ritikchaddha** [comment]
Hello @evilgensec, thank you so much for sharing this template with the community and contributing to this project 🍻

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @evilgensec 

Thank you so much for sharing this template with the community and contributing to this project 🍻

You can grab some cool PD stickers over here http://nux.gg/stickers 😄

**Comment by evilgensec** [comment]
@DhiyaneshGeek, Thank you very much for the cool Stickers !!

**Comment by evilgensec** [comment]
@DhiyaneshGeek any updates on this? I have not received any update regarding this yet.

**Comment by DhiyaneshGeek** [comment]
Hi @evilgensec 

Updated regarding ?

**Comment by evilgensec** [comment]
Regarding the PD Stickers? I haven’t received any update on them yet.

**Comment by GeorginaReeder** [comment]
Hi @evilgensec ! We're working through a bit of a backlog with stickers at the moment, so yours will indeed be on the way shortly. Thanks for your patience!

**Comment by evilgensec** [comment]
Hi @GeorginaReeder,

It's been almost two years since I last received an update regarding the swag. Could you please provide a status update when convenient?

Thank you.

**Pull request merged**
