### PR TITLE
Added template for apache-answer-version-detection-regex

### PR DESCRIPTION
**Pull request by ehsandeep**
Added template for apache-answer-version-detection-regex

### CODE REVIEW

**Comment by omranisecurity** [comment]
Please replace this information

```yaml
id: apache-answer-version-detection

info:
  name: Apache Answer Version Detection
  author: Mohammad Reza Omrani | @omranisecurity
  severity: info
  description: Extracts the version of Apache Answer from the API endpoint using regex.
  tags: apache-answer, answer
  metadata:
    shodan-query:
      - http.favicon.hash:523757057
    fofa-query:
      - icon_hash="523757057"
```

**Comment by DhiyaneshGeek** [comment]
Hi @omranisecurity i have update to proper format and added the necessary data

Let me know if it looks good 

Thanks for sharing this template and contributing to the template project 😄

**Comment by omranisecurity** [comment]
That's great, just apply these changes.
```
  author: Mohammad Reza Omrani
```
and
```
    shodan-query: http.favicon.hash:523757057
    fofa-query: icon_hash="523757057"
```

**Comment by DhiyaneshGeek** [comment]
Hi @omranisecurity we have added your Github Username as author, so it will be linked during the release.

Let me know if it works 

Thanks

**Comment by omranisecurity** [comment]
Hi @DhiyaneshGeek Everything is fine, thank you.

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @omranisecurity 

You can grab your cool PD stickers over here http://nux.gg/stickers 😄

Thanks

**Comment by omranisecurity** [comment]
Hi @DhiyaneshGeek

Thank you very much for your kindness

Regards

**Pull request merged**
