### PR TITLE
add Credentials Disclosure template to check for common secrets

### PR DESCRIPTION
**Pull request by Sy3Omda**
this template contains common regex could be found in html source files or JS

### CODE REVIEW

**Review by Sy3Omda — COMMENTED** [review]
this modification dose not work !
i have tested my original template against modified 
and here is the result !!!

2020-08-25 16_27_29-digital

**Comment by Sy3Omda** [comment]
It's working well, good job reviewing it

**Comment by bauthard** [comment]
Excellent work on this PR, thank you for sharing this with the community @Sy3Omda

**Comment by Sy3Omda** [comment]
@bauthard you are most welcome, after all
SHARING IS CARING

**Pull request merged**
