### PR TITLE
Added secret detectors for FCM API keys, mapbox API keys, razorpay client id, zapier webhooks

### PR DESCRIPTION
**Pull request by Devang-Solanki**
## Template / PR Information

    Added secret detectors for FCM API keys, mapbox API keys, razorpay client id, zapier webhooks
    References: https://docs.gitguardian.com/secrets-detection/detectors/specifics

## Template Validation

I've validated this template locally?
 [* ] YES

### CODE REVIEW

**Comment by Devang-Solanki** [comment]
Hi @pussycat0x,

Can you please run this workflow I'm sure that it will pass all the checks this time. It only failed on yaml-lint test because of a trailing white-space which I removed.

Best Regards, 
Devang

**Comment by pussycat0x** [comment]
Hi @Devang-Solanki, we are working on this.

**Comment by princechaddha** [comment]
@Devang-Solanki, thank you so much for sharing this template with the community and contributing to this project 🍻

The workflow isn't passing all of the checks as two templates have the same file names in your PR. Now it should be fixed

**Comment by Devang-Solanki** [comment]
Thanks projectdiscovery team for helping me out in this. I will contribute more in the future .

**Comment by Devang-Solanki** [comment]
Hi @princechaddha,

My file in this pr `exposures/tokens/firebase/fcm-api-token.yaml` is duplicate of `exposures/tokens/google/fcm-server-key`. If you can edit my PR and remove my file it would be great.

**Comment by princechaddha** [comment]
@Devang-Solanki I have removed that file

**Comment by Devang-Solanki** [comment]
Hi @pussycat0x,

I saw you updated the regex but can you please explain it?  

Mapbox token usually starts with **sk** or **pk** where **sk** stands for secret key and **pk** is for public.

image

Sample data : 

mapboxgl.accessToken = 'sk.eyJ1Ijoic2hlbmdsaWgiLCJhIjCf99ttaWF5bDBsMGNlaDJubGZyMGUwZXNmaCJ9.eI8KXNm5zKZXOKh0c8u9vg';"

 mapboxApiKey:
        'pk.eyJ1Ijoia3Jpc3R3IiwiYSI6ImNqbGg1N242NTFlczczdnBcf99iMjgzZ2sifQ.lUneM-o3NucXN189EYyXxQ',

**Comment by pussycat0x** [comment]
Hi @Devang-Solanki.
we have updated an extractor to match public and secret key in same template. let me know it's works for you.

**Comment by Devang-Solanki** [comment]
Hi @pussycat0x,

Everything working as expected. 

image
image

**Comment by DhiyaneshGeek** [comment]
Hi @Devang-Solanki Thank you so much for sharing this template with the community, your efforts are greatly appreciated 😄

**Pull request merged**
