### PR TITLE
Create composer-config.yaml

### PR DESCRIPTION
**Pull request by Mah3Sec**
Some juicy information that might help an attacker in information gathering about organization and might also contain some sensitive data.

### CODE REVIEW

**Comment by geeknik** [comment]
Might be good to add a matcher for 200 status to limit false positives.

**Comment by bauthard** [comment]
The matcher part still can be improved, I will update this later and merge the PR, thanks again @Mah3Sec for sharing the template.

**Comment by Mah3Sec** [comment]
Im happy to contribute .
thanks to you for adding my template

**Comment by bauthard** [comment]
Thank you @Mah3Sec, we have updated the matchers.

**Comment by Mah3Sec** [comment]
Why my name was removed from contributors ? :(

**Comment by ehsandeep** [comment]
Hey @Mah3Sec, not exactly sure what you referring, I can see the template here - [exposures/configs/composer-config.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/8fdfc64e549ed34b37650173817d8abcbccca8c3/exposures/configs/composer-config.yaml)

**Pull request merged**
