### PR TITLE
Added wp-cron.php wordpress template

### PR DESCRIPTION
**Pull request by niranc**
### Template / PR Information

- Added wp-cron.php wordpress template

It could lead attackers to a DOS attack.

- References: https://book.hacktricks.xyz/pentesting/pentesting-web/wordpress 

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### CODE REVIEW

**Comment by princechaddha** [comment]
Hello @dadevel, thank you so much for sharing this template with the community and contributing to this project  🚀

As an added measure to prevent false positives, the first request will verify if the target is running WordPress and the subsequent request will fetch the wp-cron.php endpoint.

Moreover, the template has a `dos` tag, which means it will not run by default, but it can be run with the `itags` argument.

For example: `nuclei -t vulnerabilities/wordpress/wordpress-wp-cron.yaml -u "https://127.0.0.1:8080" -itags dos`

**Comment by dadevel** [comment]
@princechaddha: I think you got something mixed up here :D

**Comment by princechaddha** [comment]
Hey @dadevel, What do you mean by something mixed up? I have added checks from `https://github.com/projectdiscovery/nuclei-templates/blob/master/technologies/wordpress-detect.yaml` 😄

**Comment by princechaddha** [comment]
Ahh got it 😂 😂

**Pull request merged**
