### PR TITLE
Add ReverseProxy/Language/CMS/Web-Framework&Tools detect

### PR DESCRIPTION
**Pull request by NkxxkN**
## Technologies Fingerprinting Base

This is far from being exhaustive but it is a good example of using multiple fingerprints.

Examples:

 - Reverse proxy:
Screenshot_2020-04-22_at_14_43_52

 - CMS
Screenshot_2020-04-22_at_15_11_47

- Web Frameworks

Screenshot_2020-04-22_at_15_20_43

### CODE REVIEW

**Comment by bauthard** [comment]
@NkxxkN This is really useful, thank you for adding this feature, I'm sure this going to help other users in many other use cases as well.

**Comment by bauthard** [comment]
Hi @NkxxkN, 

I've added the details about multiple matchers in the document at https://github.com/projectdiscovery/nuclei-templates/commit/84a6e615208261c97b9e5f67f867815d3039670f, Can you confirm if it is okay or we can add more details to help others with crafting new templates?

**Comment by NkxxkN** [comment]
All good! Thanks @bauthard

**Comment by bauthard** [comment]
Thank you for confirming this.

**Pull request merged**
