### PR TITLE
Create sap-business-connector-default-login.yaml

### PR DESCRIPTION
**Pull request by ghost**
### Template / PR Information

- Add default logins for SAP Business Connector
- References:
   - https://support.sap.com/en/product/connectors/bc.html
### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by ertygiq** [comment]
@chrisusdag I think this is not a SAP but Software AG Integration Server. 
Where did you find this vulnerability that you concluded that it's SAP?

**Review by ehsandeep — CHANGES_REQUESTED** [review]
```yaml
id: webmethod-integration-server-default-login

info:
  name: WebMethod Integration Server Default Login
  author: ChristianPoeschl,OleWagner,usdAG
  severity: high
  reference:
    - https://documentation.softwareag.com/
  metadata:
    verified: true
    shodan-query: http.favicon.hash:-234335289
  tags: default-login,webmethod

flow: http(1) && http(2)

http:
  - method: GET
    path:
      - "{{BaseURL}}/invoke/pub.file/getFile"

    matchers:
      - type: dsl
        dsl:
          - status_code == 403 || status_code == 401
          - contains(to_lower(header), 'integration server')
        condition: and

  - method: GET
    path:
      - "{{BaseURL}}/invoke/pub.file/getFile"
    headers:
      Authorization: "{{base64(username + ':' + password)}}"
      Cookie: ssnid=

    cookie-reuse: false
    threads: 10
    attack: pitchfork
    payloads:
      username:
        - Administrator
        - Developer
        - Replicator
        - SAPUser
      password:
        - manage
        - isdev
        - iscopy
        - 22101999

    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - com.wm.app.b2b.server
          - No filename supplied
        condition: and

      - type: word
        words:
          - com.wm.app.b2b.server.AccessException
          - Invalid credentials
        negative: true
        condition: and
```

@chrisusdag in the original PR, below match was with OR condition, I assume it supposed to be AND?

```yaml
      - type: word
        part: body
        words:
          - com.wm.app.b2b.server
          - No filename supplied
        condition: and
```

Also, I added flow to 1st check for detection before doing the bruteforce to avoid additonal request against any target input.

**Comment by chrisusdag** [comment]
@ehsandeep thanks for the suggestions. However the matchers do not work, when the `flow: http(1) && http(2)` line is present. I see all requests being sent, but nuclei reports no vulnerability.
The condition of the matcher was planned as `OR`, because the *Replicator* user does not seem to have permissions to access the page for reading arbitrary files, but the credentials were found valid.

@ertygiq We downloaded the software from SAP and the application contains the Title "SAP Business Connector" including the SAP logo. We activated the software using a license key provided by SAP.
The link to the references in the template points to the product page which is part of the SAP homepage.

**Comment by ertygiq** [comment]
@chrisusdag I see. That's really interesting that WebMethod Integration Server has the very same endpoint and credentials although the SAP and SoftwareAG seem to be unrelated.

**Pull request closed without merging**
