### PR TITLE
Remove Equal

### PR DESCRIPTION
**Pull request by XalfiE**

### CODE REVIEW

**Comment by ehsandeep** [comment]
Hi @XalfiE,

Is it possible that you encountered a different env file and not laravel based? as the [spec](https://laravel.com/docs/5.6/configuration#environment-configuration) says, you need `=` format, if it's a different env file, we can prepare a new template for that, let me know what you think?

**Comment by XalfiE** [comment]
Oh yeah...just checked, the target was using codeigniter

**Comment by ehsandeep** [comment]
thanks for confirming @XalfiE, in that case, it's better to have a new template as this template is tailored for laravel based env file.

**Comment by XalfiE** [comment]
Sure!

**Comment by ehsandeep** [comment]
Closing this PR as no changes are required.

**Pull request closed without merging**
