### PR TITLE
Notifying if no HTTP Host header yields directory listing

### PR DESCRIPTION
**Pull request by kazet**
### Template / PR Information

At CERT PL we detected some HTTP servers where a request with no Host header returns directory listing.

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @kazet 

Looks like a HTTP 1.0 downgrade attack, which will leak internal IP address mostly

Did you encountered Directory Listing any chances ?

**Comment by kazet** [comment]
I intended the template to activate when Directory Listing is present when no HTTP Host header is provided (we encountered such cases at CERT PL). Does it activate in any other cases?

**Comment by DhiyaneshGeek** [comment]
Hi @kazet 

Is it possible to share more information around the directory listing to me over discord 

Thanks

**Comment by kazet** [comment]
Hello, unfortunately I can't share real sites. Would it be sufficient for
you if I set up an example one?

śr., 7 sie 2024, 23:55 użytkownik Dhiyaneshwaran ***@***.***>
napisał:

**Comment by kazet** [comment]
Hello,

friendly ping ;)

**Comment by DhiyaneshGeek** [comment]
Hi @kazet ,

Checking with my teammate !

**Comment by DhiyaneshGeek** [comment]
Hi @kazet 

i have added flow, so that host is already not vulnerable to directory listing this update will not detect that

only detects directory listing on HTTP/1.0 downgrade request

Let me know if these changes works 

Looking forward to hear back from you

Thanks

**Review by ritikchaddha — APPROVED** [review]

**Pull request merged**
