### PR TITLE
Added cloudflare-nginx-detect.yaml

### PR DESCRIPTION
**Pull request by idealphase**
### Template / PR Information

- Added cloudflare-nginx-detect.yaml

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)
cloudflare-nginx-detect-shodan

cloudflare-nginx-detect-nuclei

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by idealphase** [comment]
@princechaddha Thank you for your update. Can you elaborate what is the meaning of `verified: true` in meta please?

**Comment by princechaddha** [comment]
@idealphase, thank you so much for sharing this template with the community and contributing to this project 🍻

The templates are verified before they are merged into this repository, but several do not get verified because we could not set them up and reproduce the vulnerability. However, all the templates are validated if not verified before they are merged into this repository to avoid any false positives/negatives.

We have now started explicitly marking all of the verified templates so that contributors will also be able to help us verify the templates which are marked as `verified: false`.

**Comment by idealphase** [comment]
@princechaddha  Thank you for your clarification. I got your point to avoid any false positives/negatives. So, It means contributor can add `verified: true` by themselves with figure artifact likes preceding image or your PD team will add it before approve and merging.

**Comment by princechaddha** [comment]
@idealphase, The contributors can also mark the templates as verified if they have tested the templates themselves and provide the preceding debug data/images in the PR description.

**Comment by idealphase** [comment]
@princechaddha  I got it. Thank you so much for your clarification. I'll add `verified: true` with debug images in the next PR. :)

**Pull request merged**
