### PR TITLE
Add FortiLogger Unauthenticated Arbitrary File Upload

### PR DESCRIPTION
**Pull request by dwisiswant0**

### CODE REVIEW

**Comment by pikpikcu** [comment]
Hey @dwisiswant0, can you update this templates? this doesn't works. 
check demo: http://85.96.242.30:5000/shared/GetProductInfo
#### 
nooo

#### Vulnerable
demo

**Comment by DhiyaneshGeek** [comment]
@dwisiswant0 is this template is for detection ?

**Comment by ehsandeep** [comment]
@pikpikcu it should work now, can you confirm?

**Comment by pikpikcu** [comment]
@ehsandeep yeah this worked 🎉

**Pull request merged**
