### PR TITLE
added technology regexes from wappalyzer

### PR DESCRIPTION
**Pull request by hakluke**
Hey guys,

I love what you're doing here. I added a stack of technology fingerprinting regexes that are used in Wappalyzer. Hope this helps!

hakluke

### CODE REVIEW

**Comment by bauthard** [comment]
Hi @hakluke, 

This is a great effort, and to make it more simple all this can be done with single templates as well as `base` URL is same in all case, so you just make **one** request and detect all the techs at once, do you want us to prepare all this in single template before merging this?

**Comment by hakluke** [comment]
That does make a lot of sense @bauthard! I don't have time to do it this week but if someone else wants to do it go for it.

**Comment by akhil-reni** [comment]
@bauthard how do we return the technology in response?

For example something like this 
```
id: 1C-Bitrix

info:
  name: 1C-Bitrix
  author: hakluke
  severity: low

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
    matchers:
      - type: regex
        part: body
        regex:
          - "(?:<link[^>]+components/bitrix|(?:src|href)=\"/bitrix/(?:js|templates))"
          - "<a-scene[^<>]*>"
```

It will return 1C-Bitrix but I have two regexes for two different technologies?

**Comment by bauthard** [comment]
Hey @akhil-reni, multiple matchers can be used with single target, and all matches will be listed in a new line, so we are going all create a single template including all the fingerprints listed in this PR. 

```
[tech-detect:wordpress] [http] http://test.com/
[tech-detect:apache] [http] http://test.com/
[tech-detect:wordpress] [http] http://test.com/
[tech-detect:java] [http] http://test.com/
[tech-detect:xyz] [http] http://test.com/
[tech-detect:abc] [http] http://test.com/
```

here is an example for using multiple matches against one request:- https://github.com/projectdiscovery/nuclei-templates/blob/master/subdomain-takeover/detect-all-takeovers.yaml

**Comment by hakluke** [comment]
That makes total sense, I didn't know this was possible!

**Comment by bauthard** [comment]
This is done at https://github.com/projectdiscovery/nuclei-templates/commit/3b8e5ae2299f2de4aab03a44a7b08e2b4e54d6ae, we ported into a single template, again thank you so much @hakluke for your comprehensive work on this, this is going to be useful for tech fingerprinting, we also would like to extend an invite to you for our [chaos platform](https://chaos.projectdiscovery.io/), if you are interested please fill this [contributors form](https://forms.gle/Lpc9Lnkna3g96pHB6). 

```bash
> chaos -d hackerone.com -silent | httpx -silent | nuclei -t tech-detect.yaml 


[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[WRN] Latest version of nuclei-templates installed: v1.0.0
[INF] [tech-detect] Loaded template Wappalyzer Technology Detection (@hakluke) [informative]

[tech-detect:jsdelivr] [http] https://docs.hackerone.com/
[tech-detect:react] [http] https://docs.hackerone.com/
[tech-detect:gatsby] [http] https://docs.hackerone.com/
[tech-detect:react] [http] https://www.hackerone.com/
[tech-detect:jsdelivr] [http] https://api.hackerone.com/
```

**Comment by bauthard** [comment]
@akhil-reni FYI, this is done and the template is updated.

**Comment by hakluke** [comment]
Awesome work @bauthard - thanks for merging them, sorry I didn't get to it earlier.

**Pull request closed without merging**
