### PR TITLE
twilio-api.yaml

### PR DESCRIPTION
**Pull request by 5hank4r**
### Template / PR Information

I've noticed that the template you mentioned isn't capable of extracting all the keys. This template currently only checks for the keyword "SK" as specified in my template.

Mention template (regex)
image

New Regex
image

### Template Validation

I've validated this template locally?
- [ y] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @5hank4r The currently twilio API key regex is meant to detect the API keys only.

We can have separate template to detect the twilio account secret, auth token and account sid

Looking forward to hear back from you

Thanks

**Comment by 5hank4r** [comment]
@DhiyaneshGeek  I've checked all the templates with Nuclei, but I couldn't find any Twilio account secret, auth token, or account SID. If there isn't a template for this, I can create one.

**Comment by DhiyaneshGeek** [comment]
Hi @5hank4r i can see those regex are already present in few of the templates

image

You can join our [discord server](https://discord.com/invite/projectdiscovery). you can DM over there

Thanks

**Comment by 5hank4r** [comment]
@DhiyaneshGeek okay sure

**Comment by DhiyaneshGeek** [comment]
Hi @5hank4r Can we close this PR , since we have regex for this already

Looking forward to hear back from you

Thanks

**Pull request closed without merging**
