### PR TITLE
Add  OSINT templates

### LINKED ISSUE #6761: Osint templates
Hello folks!
Does Nuclei team have an interest on open contributions to OSINT templates?
I was imagining to contributing your project with something like the Sherlock (https://github.com/sherlock-project/sherlock) tools does: fetch a username across many social media platforms.

Would this be interesting?

### PR DESCRIPTION
**Pull request by dwisiswant0**
### Template / PR Information

- Add OSINT templates (close #6761)
- References:

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Review by ehsandeep — COMMENTED** [review]
@dwisiswant0, very nice work / automation. Can we add `https://github.com/sherlock-project/sherlock` as a reference in all templates?

**Comment by dwisiswant0** [comment]
> @dwisiswant0, very nice work / automation. Can we add `https://github.com/sherlock-project/sherlock` as a reference in all templates?

Unfortunately I converted it from the WhatsMyName project by. Please see README under `osint` directory of this PR.

**Review by ehsandeep — APPROVED** [review]
```console
$ nuclei -t osint/ -var user=ehsandeep

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v2.8.9

		projectdiscovery.io

[INF] Using Nuclei Engine 2.8.9 (latest)
[INF] Using Nuclei Templates 9.3.7 (latest)
[INF] Templates added in last update: 58
[INF] Templates loaded for scan: 620
[gitlab] [http] [info] https://gitlab.com/ehsandeep
[picsart] [http] [info] https://picsart.com/u/ehsandeep
[telegram] [http] [info] https://t.me/ehsandeep
[twitter-archived-tweets] [http] [info] http://archive.org/wayback/available?url=https://twitter.com/ehsandeep/status/*
[smule] [http] [info] https://www.smule.com/api/profile/?handle=ehsandeep
[giters] [http] [info] https://giters.com/ehsandeep
[instagram] [http] [info] https://www.picuki.com/profile/ehsandeep
[twitter] [http] [info] https://nitter.net/ehsandeep
[github] [http] [info] https://github.com/ehsandeep
```

**Comment by zeroc00I** [comment]
Thank u guys =), that was an epic work and bigger that i could imagine when i propose that

**Review by princechaddha — APPROVED** [review]

**Pull request merged**
