### PR TITLE
Added template for f5-admin-interface

### PR DESCRIPTION
**Pull request by ehsandeep**
Added template for f5-admin-interface

### CODE REVIEW

**Review by ritikchaddha — APPROVED** [review]

**Comment by ritikchaddha** [comment]
Hello @javrav2, thank you so much for sharing this template with the community and contributing to this project 🍻

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

**Comment by DhiyaneshGeek** [comment]
Hi @javrav2 

Thank you so much for sharing this template with the community and contributing to this project 🍻

You can grab some cool PD stickers over here http://nux.gg/stickers 😄

**Comment by javrav2** [comment]
Any idea why none of the stickers have been sent? Sorry just wanted to get some cool stickers Sent from my iPhoneOn Nov 3, 2024, at 10:34 PM, Dhiyaneshwaran ***@***.***> wrote:﻿
Hi @javrav2
Thank you so much for sharing this template with the community and contributing to this project 🍻
You can grab some cool PD stickers over here http://nux.gg/stickers 😄

**Comment by techcraver** [comment]
> Any idea why none of the stickers have been sent? Sorry just wanted to get some cool stickers Sent from my iPhoneOn Nov 3, 2024, at 10:34 PM, Dhiyaneshwaran ***@***.***> wrote:﻿ Hi @javrav2 Thank you so much for sharing this template with the community and contributing to this project 🍻 You can grab some cool PD stickers over here http://nux.gg/stickers 😄 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

Hey @javrav2 !
I'm on the community team and help with stickers. Did you submit recently? We were having an issue with our fulfillment workflow and I want to ensure we have your request and your stickers get sent out!

**Comment by javrav2** [comment]
I resubmitted the form last night, not sure if the request was received Sent from my iPhoneOn Jan 11, 2025, at 9:31 AM, Jason Harris ***@***.***> wrote:﻿

Any idea why none of the stickers have been sent? Sorry just wanted to get some cool stickers Sent from my iPhoneOn Nov 3, 2024, at 10:34 PM, Dhiyaneshwaran @.> wrote:﻿ Hi @javrav2 Thank you so much for sharing this template with the community and contributing to this project 🍻 You can grab some cool PD stickers over here http://nux.gg/stickers 😄 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.>

Hey @javrav2 !
I'm on the community team and help with stickers. Did you submit recently? We were having an issue with our fulfillment workflow and I want to ensure we have your request and your stickers get sent out!

**Comment by techcraver** [comment]
Ok perfect! I see it now. 
I'll get on it! :)

**Pull request merged**
