### PR TITLE
Subdomain Takeover Directory

### PR DESCRIPTION
**Pull request by melbadry9**
worksites.net takeover

### CODE REVIEW

**Comment by bauthard** [comment]
This is nice @melbadry9, I was thinking of porting all the fingerprints of takeovers and create new folder with all the fingerprints in it and you already submitted one, thank you for the pull request.

**Comment by melbadry9** [comment]
@bauthard

- Any chance we could add all fingerprints in one template and specify a service name for every fingerprint to be printed on match?

 - This could help reduce the number of requests.

**Comment by bauthard** [comment]
Hi @melbadry9, 

Great suggestion, surely this will be helpful, so I'm going to create a Github issue to pick it up next time we work on this.

**Comment by bauthard** [comment]
done, created an issue at https://github.com/projectdiscovery/nuclei/issues/25

**Pull request merged**
