### PR TITLE
Added check for spoofable SPF records

### PR DESCRIPTION
**Pull request by binaryfigments**
Added DNS check for SPF. The PTR mechanism in an SPF records is spoofable. A bad actor can create a VPS with a mailserver and give it any PTR record that it wants an most VPS providers. Valid YAML, chacked by http://www.yamllint.com/

### CODE REVIEW

**Comment by binaryfigments** [comment]
Testrun:

```
user@laptop:~/Nuclei/dev$ cat domains.txt  | nuclei -t nuclei-templates/dns/spoofable-spf-records-ptr.yaml 

                       __     _
     ____  __  _______/ /__  (_)
    / __ \/ / / / ___/ / _ \/ /
   / / / / /_/ / /__/ /  __/ /
  /_/ /_/\__,_/\___/_/\___/_/   v2.1.1

		projectdiscovery.io

[WRN] Use with caution. You are responsible for your actions
[WRN] Developers assume no liability and are not responsible for any misuse or damage.
[INF] Loading templates...
[INF] [spoofable-spf-records-ptr] Find spoofable SPF records containing the PTR mechanism (@binaryfigments) [info]
[INF] Using 1 rules (1 templates, 0 workflows)
[spoofable-spf-records-ptr] [dns] [info] eerstekamer.nl
[spoofable-spf-records-ptr] [dns] [info] functiegebouwrijksoverheid.nl
[spoofable-spf-records-ptr] [dns] [info] kempischbedrijvenpark.com
[spoofable-spf-records-ptr] [dns] [info] kabga.aw
[spoofable-spf-records-ptr] [dns] [info] mobiliteitsbank.nl
[spoofable-spf-records-ptr] [dns] [info] montfoort.nl
[spoofable-spf-records-ptr] [dns] [info] nieuwlanderfgoed.nl
[spoofable-spf-records-ptr] [dns] [info] noord-hollandsarchief.nl
[spoofable-spf-records-ptr] [dns] [info] noordelijkbelastingkantoor.nl
[spoofable-spf-records-ptr] [dns] [info] oudewater.nl
[spoofable-spf-records-ptr] [dns] [info] parismou.org
[spoofable-spf-records-ptr] [dns] [info] rijkstalentencentrum.nl
[spoofable-spf-records-ptr] [dns] [info] voordejeugd.nl
[spoofable-spf-records-ptr] [dns] [info] voorst.nl
[spoofable-spf-records-ptr] [dns] [info] vrh.nl
[spoofable-spf-records-ptr] [dns] [info] werkenbijdeoverheid.nl
[spoofable-spf-records-ptr] [dns] [info] werkplus.rijkstalentencentrum.nl
```

**Comment by binaryfigments** [comment]
Also added e-mail service detector by MX records from DNS.

**Review by dwisiswant0 — APPROVED** [review]
This is epic. :fire:

**Comment by bauthard** [comment]
@binaryfigments thank you for submitting this, this is creative and the first PR for DNS related template as well.

> The PTR mechanism in an SPF records is spoofable.

Do you have a reference or study material that we can add to this template?

**Review by bauthard — APPROVED** [review]

**Comment by binaryfigments** [comment]
PTR lookups are slow and unreliable.

Beside that, I came across situations where the SPF check was PASS when the mailserver has a PTR record under the domain name of the SPF record. What I did, I started a VPS at DigitalOcean, gave it a PTR record like `mailserver.target.domain` and with sending an email from that VPS to `somebody@target.domain`. The target mailserver does the SPF check, sees that the IP address of my VPS had a PTR record with a subdomain under `target.domain` and it will PASS.

And the RFC tells us: do not use:
https://tools.ietf.org/html/rfc7208#section-5.5

There are still mailservers in use that are using the old RFC:
https://tools.ietf.org/html/rfc4408#section-5.5

**Comment by bauthard** [comment]
Thank you @binaryfigments for adding more info to this.

**Pull request merged**
