### PR TITLE
add phpmyadmin-default-login

### PR DESCRIPTION
**Pull request by Natto97**
### Template / PR Information

- Added phpMyAdmin Default Login
- References: https://www.phpmyadmin.net/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by princechaddha** [comment]
Hello @Natto97, thank you so much for sharing this template with the community and contributing to this project  🚀

As the provided template caused false positives, we modified the template to work with the latest PHPMyAdmin `5.1.3`. If you could share the version using which you created the template, we could add a separate template for that as well.

**Comment by Natto97** [comment]
Hello @princechaddha,My test environment is  phpMyAdmin `4.4.15.6`

**Comment by Natto97** [comment]
I modified the code to be compatible with phpMyAdmin 4.4.15.6, PHPMyAdmin 5.1.3.
The following is the packet of phpMyAdmin successful login.

## phpMyAdmin 4.4.15.6
```
HTTP/1.1 302 Found
Date: Sat, 30 Apr 2022 08:06:07 GMT
Server: Apache/2.4.10 (Debian)
X-Powered-By: PHP/5.3.29
Set-Cookie: phpMyAdmin=5818f02700729aee513e5bc081151096a5b7368f; path=/; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, max-age=10800, pre-check=10800
Last-Modified: Mon, 21 May 2018 06:36:35 GMT
Set-Cookie: pma_collation_connection=utf8_unicode_ci; expires=Mon, 30-May-2022 08:06:07 GMT; path=/; httponly
Set-Cookie: pma_iv-1=VJbEs5I4nWKcoWKi0SDNqQ%3D%3D; expires=Mon, 30-May-2022 08:06:07 GMT; path=/; httponly
Set-Cookie: pmaUser-1=inkfwrr7RBgAGQiKWQFwaQ%3D%3D; expires=Mon, 30-May-2022 08:06:07 GMT; path=/; httponly
Set-Cookie: pmaPass-1=K0z0K9YkPqDaQg7rCquQ1A%3D%3D; path=/; httponly
X-ob_mode: 1
Location: http://xxx.xxx.xxx.xxx:8086/index.php?collation_connection=utf8mb4_unicode_ci&token=0cbfbc045af95dc016c44c64091a3232
Vary: Accept-Encoding
Content-Length: 0
Connection: close
Content-Type: text/html
```
## PHPMyAdmin 5.1.3
```
HTTP/1.1 302 Found
Date: Sat, 30 Apr 2022 08:55:05 GMT
Server: Apache/2.4.53 (Debian)
X-Powered-By: PHP/8.0.18
Set-Cookie: phpMyAdmin=3808a1a54ec5fa0b1a9e1280caa9e596; path=/; HttpOnly; SameSite=Strict
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: private, max-age=10800
Last-Modified: Fri, 11 Feb 2022 04:16:06 GMT
Set-Cookie: phpMyAdmin=952ae8baba5fde807d083093a41bdc71; path=/; HttpOnly; SameSite=Strict
Set-Cookie: pmaUser-1=%7B%22iv%22%3A%22DYPwPsbLVEztSZvgBW%2BAMQ%3D%3D%22%2C%22mac%22%3A%22f5bdb86c004e576b50868c247ff98d6d00309d50%22%2C%22payload%22%3A%22q9v21waHj%2BvGjlkx6lh3Gw%3D%3D%22%7D; expires=Mon, 30-May-2022 08:55:05 GMT; Max-Age=2592000; path=/; HttpOnly; SameSite=Strict
Set-Cookie: pmaAuth-1=%7B%22iv%22%3A%226s1pOG%2BoA3XPQJhS8BRgrg%3D%3D%22%2C%22mac%22%3A%223a1e188767710c8e43711a30886b436a37b27da7%22%2C%22payload%22%3A%22MrguPvhKarJVTNUC%5C%2FGoZHrlb09O3OaeqKzB2rxmhAtg%3D%22%7D; path=/; HttpOnly; SameSite=Strict
X-ob_mode: 1
Location: /index.php?route=/&route=%2F
Vary: Accept-Encoding
Content-Length: 0
Connection: close
Content-Type: text/html; charset=utf-8
```

**Comment by princechaddha** [comment]
@Natto97, Sorry for the delay on his PR. The template updated by you will result in false positives. Try running it on `http://185.66.10.102:80`.

I have made a few more changes to cover both versions. Let me know if the made changes look good to you.

**Comment by Natto97** [comment]
Thanks a lot, no problem anymore.

**Pull request merged**
