### PR TITLE
Add detection of Rise Up learning platform.

### PR DESCRIPTION
**Pull request by righettod**
### Template / PR Information

Hi,

This PR propose a template to detect an instance of the [Rise Up](https://www.riseup.ai) learning platform.

- References: https://www.riseup.ai

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

Proof:

image

### Additional Details (leave it blank if not applicable)

None

### Additional References:

None

### CODE REVIEW

**Comment by tess-ss** [comment]
Hi @righettod, 

Thank you so much for sharing this template with the community and contributing to this project 🍻

**Comment by righettod** [comment]
Hi @tess-ss You are welcome 😃

**Review by princechaddha — APPROVED** [review]

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
@righettod thank you so much for sharing this template with the community and contributing to this project 🍻

**Comment by righettod** [comment]
> @righettod thank you so much for sharing this template with the community and contributing to this project 🍻

You are welcome, it is always a pleasure to work with you 💯 
 
> Do Let know us know if the mirror changes in the template works or not :)

Seemed OK:

image

**Pull request merged**
