### PR TITLE
Discourse added 

### PR DESCRIPTION
**Pull request by pdelteil**
Code to detect possible takeover of Discourse accounts.

### CODE REVIEW

**Comment by bauthard** [comment]
Hi @pdelteil, 

Can you please share or add some reference to this takeover?

**Comment by pdelteil** [comment]
> Hi @pdelteil,
> 
> Can you please share or add some reference to this takeover?

Sure @bauthard 

Report: https://hackerone.com/reports/423022
Sample: http://jomaxrotest.trydiscourse.com/

**Comment by bauthard** [comment]
Hi @pdelteil, 

I was reviewing this PR and found a few existing templates that you are updating them with your local changes, can you make sure to fix this or close this PR and submit only the new ones you want to submit?

**Comment by pdelteil** [comment]
@bauthard  I'm sorry for the additional commits. I will close this PR and add create a new one with only 1 commit.

**Comment by bauthard** [comment]
Thanks a lot, @pdelteil, Having PR per template make it easy for review / for making any changes.

**Pull request closed without merging**
