### PR TITLE
Split up springboot-detect

### PR DESCRIPTION
**Pull request by wdahlenburg**
This is currently a work in progress to address #729. Ideally all templates can support versions 1 and 2 of springboot actuators. 

I would argue that only the relevant spring actuators should have templates instead of all actuators. The healthcheck actuator is generally uninteresting. Info is very difficult to write a signature for and will likely not contain sensitive information. The refresh, shutdown, and restart endpoints should likely not be hit in an automated fashion.

@that_juan_ and @dwisiswant0 if you have examples of some of the missing actuators, that would be a huge help. 

At minimum I consider these impactful and worth adding, which still need to be done:
- [x] loggers

Please add comments and suggestions. This will require a good number of samples to test against.

### CODE REVIEW

**Comment by wdahlenburg** [comment]
The heapdump check will generally require the -timeout parameter to be set to a large value, such as 90+ because of the very large file being returned. I did notice that some servers sent the transfer-encoding as chunked, which unfortunately does not have to send a content-length header, which is why the dsl check is an "or" on the size. 

Spring version 1 will send the heapdump back in a gzip format. I specified the gzip magic bytes to capture this. Spring version 2 sends the heapdump uncompressed, which normally starts with JAVA PROFILE.

**Comment by bauthard** [comment]
Thank you for splitting the template into more meaningful ways @wdahlenburg, we will be adding a template for the other three endpoints you listed and later test to make sure everything is covered and matched all the cases.

**Comment by dwisiswant0** [comment]
lgtm

**Comment by bauthard** [comment]
@wdahlenburg thank you for working on this, we need to come up with some ways to detect `heapdump` with more ease, most probably something that needs to add from our side at the engine level, we will keep this in mind in the next release.

**Comment by ehsandeep** [comment]
@wdahlenburg FYI, We have added the support of reading X size of response with `max-size`, so we don't have to wait to read the whole response and this allows us to detect `/heapdump` file reliably all the time, I've updated the template here https://github.com/projectdiscovery/nuclei-templates/commit/450254cd3d7b973d369b8b331c66bc76a35f2a1d.

**Comment by wdahlenburg** [comment]
Cool! That's a huge improvement over needing to set a long timeout.

**Comment by tanujjane** [comment]
@ehsandeep You can add this
datahub/actuator/heapdump
datahub/heapdump

**Comment by ehsandeep** [comment]
@tanujjane any reference for this path?

**Pull request merged**
