### PR TITLE
Tomcat Manager: detection and bf templates fixes for newver versions

### PR DESCRIPTION
**Pull request by sinKettu**
### Template / PR Information

- Fixed 'public-tomcat-manager', 'tomcat-default-login'

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

Previous versions of templates I mentioned above is not fully fitting newer versions of Apache server. I've tested these templates on servers of company I'm working in and these templates were not able to detect Tomcat and BF credentials. Last version of OpenVAS detected it successfully in the same time. I've tested why and offer you fixes.

Tested on `Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips PHP/5.6.40`

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
@sinKettu The current matcher is working well, let me know if i'm missing something :)

**Comment by DhiyaneshGeek** [comment]
@sinKettu the current template detects on both 401 and 200 status code pages, let me know if i'm wrong

**Comment by sinKettu** [comment]
@DhiyaneshGeek Ok, I'll try to share screenshot in a day

**Comment by DhiyaneshGeek** [comment]
@sinKettu as far seeing the screenshot "Apache Tomcat" keyword is not there in the response ?

**Comment by sinKettu** [comment]
@DhiyaneshGeek Yeap

**Comment by sinKettu** [comment]
@DhiyaneshGeek I would like to suggest the following changes (uncommited). It will cover previous cases and my case. I've added matcher for `Tomcat Manager` word and specified matching part as `raw`

``` yaml
    matchers-condition: and
    matchers:
      - type: word
        part: raw
        words:
          - "Apache Tomcat"
          - "Tomcat Manager"
        condition: or

      - type: status
        status:
          - 401
          - 200
        condition: or
```

**Comment by DhiyaneshGeek** [comment]
@sinKettu thank you so much for sharing this template with the community and contributing to this project 🍻.

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by sinKettu** [comment]
@DhiyaneshGeek  Thank you so much! But I have question. Could I know reason why you declined changes of `tomcat-default-login.yaml` ([my commit](https://github.com/projectdiscovery/nuclei-templates/pull/6002/commits/ba9e9e3a0e9fd321bcf43293e6760852c7281187))? I still believe that `Hostname` word-matcher is too generalized and is not a sign of presence of Tomcat. I would appreciate if you can answer.

**Comment by DhiyaneshGeek** [comment]
@sinKettu `Hostname` matcher was present in the response, i tried setting up instance to cross check it at my end

Hope this help :)

**Comment by sinKettu** [comment]
@DhiyaneshGeek I agree that It could be present. But don't you think this is not a very accurate marker?

**Pull request merged**
