### PR TITLE
SSRF based templates improved

### PR DESCRIPTION
**Pull request by iamxhunt3r**
### Template information

SSRF-based templates were improved as they use {{interactsh-url}} parameter.

### Now why it's necessary to change `oast.me` or `oast.fun`  to  `{{interactsh-url}}`?

- For compliance issues and keeping logs.

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @iamxhunt3r , it's already discussed over the past https://github.com/projectdiscovery/nuclei-templates/pull/7770#issuecomment-1655945062

Feel free to join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again!

**Comment by iamxhunt3r** [comment]
Please check the PR once, It contains improved tags, also templates with SSRF are improved with interactsh variable which will be better for custom interactsh logs and compliance.
@ehsandeep

**Comment by ehsandeep** [comment]
@iamxhunt3r thanks for the PR! But these changes are actually not applicable as these templates are not or need to be based on OAST checks, in these cases static URL is used instead of a dynamic one as these are **response-based SSRF** checks and not ping (interaction) based, while it is still possible to use dynamic URL, but it's not the best option when you have Full response based SSRF, oast based check should be only used when it's the only way to detect, i.e blind SSRF and similar issues.

**Comment by iamxhunt3r** [comment]
Got it.
Thanks @DhiyaneshGeek @ehsandeep

**Pull request closed without merging**
