### PR TITLE
Added template for docker-ports-detection

### PR DESCRIPTION
**Pull request by pdteamx**
Added template for docker-ports-detection

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @javrav2 

Thanks for sharing the template with the community

The template get's match against honeypot server 

Kindly update the weak matcher

Thanks

**Comment by savushkin-yauheni** [comment]
Hi @javrav2 
you just missed `matchers-condition: and`

**Comment by DhiyaneshGeek** [comment]
Hi @savushkin-yauheni 

Nope he already added `condition: and`

The keywords were weak which get's matched against honeypot server

**Comment by princechaddha** [comment]
We already have a template for this here: https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/exposed-docker-api.yaml. Users are expected to supply hosts along with the ports as input. We don’t hardcode the port in the templates instead, we focus on identifying vulnerabilities on the provided host and port.

**Comment by DhiyaneshGeek** [comment]
Hi @javrav2 

Since we already have a template , so we are closing this PR 

Thanks

**Pull request closed without merging**
