### PR TITLE
Security Checks for Magento - Templates and workflow

### PR DESCRIPTION
**Pull request by Techbrunch**
One thing I'm not really happy with is that there are 3 requests in the `magento-detect` template and they will all be ran. 

Is there a way to say in a template that if the first request is true then don't run the rest ?

### CODE REVIEW

**Comment by Techbrunch** [comment]
I fixed the `magento-admin-panel` since now you are following the redirects the cookie check does not make sense anymore. Also the check on the title will break if the language is different.

**Comment by ehsandeep** [comment]
@Techbrunch only looking for status or single matcher will produce false-positive results as many web servers return 200 for anything you request, I'm looking for some reference to include additional matchers for `magento-unprotected-dev-files`

**Comment by Techbrunch** [comment]
Why did you change the workflow ? Magento related templates should only by ran if Magento is detected right ?

**Comment by ehsandeep** [comment]
There was a syntax error @Techbrunch, I just noticed we have [magmi-workflow](https://github.com/projectdiscovery/nuclei-templates/blob/master/workflows/magmi-workflow.yaml) so the following workflow for magento looks good to you?


```yaml
workflows:
  - template: technologies/magento-detect.yaml
    subtemplates:
      - template: exposures/configs/magento-config.yaml
      - template: exposed-panels/magento-admin-panel.yaml
      - template: vulnerabilities/magento/
```

**Comment by Techbrunch** [comment]
@ehsandeep Yeah I initially thought that magmi was a Magento plugin, that's why I included it as a subtemplate.

**Comment by ehsandeep** [comment]
Thank you @Techbrunch, this is a good collection for quick security checks for websites running on Magento, merging this PR now.

**Pull request merged**
