### PR TITLE
Fix matched OS version information

### PR DESCRIPTION
**Pull request by lu4nx**
### Template / PR Information

Same fingerprints used by Windows XP SP1~SP3 and Windows 2000

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### CODE REVIEW

**Comment by lu4nx** [comment]
@DhiyaneshGeek Hello, this PR has not been processed for a long time, do you need my assistance?

**Comment by DhiyaneshGeek** [comment]
@lu4nx Sure, @pussycat0x is reviewing  it now will get it merged today

Thank you for sharing this template with the community and for your contribution to this project. Your efforts are greatly appreciated. Cheers!

**Comment by pussycat0x** [comment]
Hi @lu4nx can you share a debug response for this finger print?.it would be help to validate.

**Comment by lu4nx** [comment]
@pussycat0x Hi,

For Windows XP SP3:
```
[DBG] Protocol request variables: 
	1. Hostname => 192.168.56.115
	2. Host => 192.168.56.115

[INF] [rdp-detect] Dumped Network request for 192.168.56.115:3389
00000000  03 00 00 2a 25 e0 00 00  00 00 00 43 6f 6f 6b 69  |...*%......Cooki|
00000010  65 3a 20 6d 73 74 73 68  61 73 68 3d 74 65 73 74  |e: mstshash=test|
00000020  0d 0a 01 00 08 00 0b 00  00 00                    |..........| address=192.168.56.115:3389
[DBG] Protocol response variables: 
	1. Hostname => 192.168.56.115
	2. template-info => {Windows RDP Detection pr .... ap[verified:true] <nil> }
	3. ip => 192.168.56.115
	4. raw => 
                  �4
	5. template-id => rdp-detect
	6. Host => 192.168.56.115
	7. interactsh-server => 
	8. matched => 192.168.56.115:3389
	9. data => 
                   �4
	10. host => 192.168.56.115
	11. request => *%�Cookie: mstshash=test  

	12. type => network
	13. template-path => /home/lu4nx/nuclei-templa .... detection/rdp-detect.yaml

[2023-01-13 14:01:32] [rdp-detect:win2000/winxp] [network] [info] 192.168.56.115:3389
[DBG] [rdp-detect] Dumped Network response for 192.168.56.115:3389

00000000  03 00 00 0b 06 d0 00 00  12 34 00                 |.........4.|
[WRN] Could not make network request for 192.168.56.115: no port provided in network protocol request
```

For Windows XP SP2:
```
[DBG] Protocol request variables: 
	1. Host => 192.168.56.114
	2. Hostname => 192.168.56.114

[INF] [rdp-detect] Dumped Network request for 192.168.56.114:3389
00000000  03 00 00 2a 25 e0 00 00  00 00 00 43 6f 6f 6b 69  |...*%......Cooki|
00000010  65 3a 20 6d 73 74 73 68  61 73 68 3d 74 65 73 74  |e: mstshash=test|
00000020  0d 0a 01 00 08 00 0b 00  00 00                    |..........| address=192.168.56.114:3389
[DBG] Protocol response variables: 
	1. ip => 192.168.56.114
	2. host => 192.168.56.114
	3. data => 
                   �4
	4. raw => 
                  �4
	5. template-path => /home/lu4nx/nuclei-templa .... detection/rdp-detect.yaml
	6. matched => 192.168.56.114:3389
	7. type => network
	8. template-info => {Windows RDP Detection pr .... ap[verified:true] <nil> }
	9. Host => 192.168.56.114
	10. interactsh-server => 
	11. template-id => rdp-detect
	12. Hostname => 192.168.56.114
	13. request => *%�Cookie: mstshash=test  


[2023-01-13 14:03:02] [rdp-detect:win2000/winxp] [network] [info] 192.168.56.114:3389
[DBG] [rdp-detect] Dumped Network response for 192.168.56.114:3389

00000000  03 00 00 0b 06 d0 00 00  12 34 00                 |.........4.|
[WRN] Could not make network request for 192.168.56.114: no port provided in network protocol request
```

For Windows XP SP1:

```
[DBG] Protocol request variables: 
	1. Hostname => 192.168.56.119
	2. Host => 192.168.56.119

[INF] [rdp-detect] Dumped Network request for 192.168.56.119:3389
00000000  03 00 00 2a 25 e0 00 00  00 00 00 43 6f 6f 6b 69  |...*%......Cooki|
00000010  65 3a 20 6d 73 74 73 68  61 73 68 3d 74 65 73 74  |e: mstshash=test|
00000020  0d 0a 01 00 08 00 0b 00  00 00                    |..........| address=192.168.56.119:3389
[DBG] Protocol response variables: 
	1. template-info => {Windows RDP Detection pr .... ap[verified:true] <nil> }
	2. raw => 
                  �4
	3. Hostname => 192.168.56.119
	4. ip => 192.168.56.119
	5. Host => 192.168.56.119
	6. matched => 192.168.56.119:3389
	7. request => *%�Cookie: mstshash=test  

	8. host => 192.168.56.119
	9. data => 
                   �4
	10. template-path => /home/lu4nx/nuclei-templa .... detection/rdp-detect.yaml
	11. interactsh-server => 
	12. type => network
	13. template-id => rdp-detect

[2023-01-13 14:23:51] [rdp-detect:win2000/winxp] [network] [info] 192.168.56.119:3389
[DBG] [rdp-detect] Dumped Network response for 192.168.56.119:3389

00000000  03 00 00 0b 06 d0 00 00  12 34 00                 |.........4.|
[WRN] Could not make network request for 192.168.56.119: no port provided in network protocol request
```

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by pussycat0x** [comment]
Hi @lu4nx  Thanks for sharing the debug data :)

**Pull request merged**
