### PR TITLE
Improved AXIS detection

### PR DESCRIPTION
**Pull request by f1she3**
### Template / PR Information

- Added the hash and the path of the AXIS logo, found on many AXIS devices. Re-opened this PR (closed by mistake).

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by princechaddha** [comment]
Hello @f1she3, thank you so much for sharing this template with the community and contributing to this project  🚀

Instead of adding more endpoints, I think one should be sufficient to detect Live View AXIS Network cameras. What do you think?

**Comment by f1she3** [comment]
> Hello @f1she3, thank you so much for sharing this template with the community and contributing to this project  🚀
> 
> Instead of adding more endpoints, I think one should be sufficient to detect Live View AXIS Network cameras. What do you think?
> 

Hi !

I wanted to keep the work done on the previous template. I think it's good to have different endpoints to cover the different versions of the software. However, if only one of them had to be kept, I think it should be the logo endpoint I added.

**Comment by f1she3** [comment]
Do you think I should edit the PR then ?

**Comment by princechaddha** [comment]
@f1she3, I made some changes. Let me know if it looks good to you?

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
