### PR TITLE
Multiple login panel templates

### PR DESCRIPTION
**Pull request by Splint3r7**
### Template / PR Information

- Multiple login panel templates

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks so much for your contribution @Splint3r7 ! :)

**Comment by Splint3r7** [comment]
@DhiyaneshGeek  all good here, do you think if any changes are required?

**Comment by DhiyaneshGeek** [comment]
Hi @Splint3r7 

i'm looking into this currently

**Comment by Splint3r7** [comment]
Hi @ritikchaddha , could you please review and merge this PR if everything looks good? My other branches are currently including these templates as well, and merging this would allow me to push new templates from the other branches more smoothly. Thank you!

**Review by ritikchaddha — APPROVED** [review]

**Comment by ritikchaddha** [comment]
Hello @Splint3r7, thank you so much for sharing this template with the community and contributing to this project 🍻

**Pull request merged**
