### PR TITLE
Add detection of IBM API Connect Developer Portal instances. 

### PR DESCRIPTION
**Pull request by righettod**
### Template / PR Information

Hi,

This PR propose a template to detect instance of the **IBM API Connect Developer Portal** software.

References:

- https://github.com/ibm-apiconnect/devportal
- https://www.ibm.com/products/api-connect/developer-portal

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

image

Hosts used for the test found via Shodan and/or https://crt.sh :

```
https://194.78.26.205:9091
https://194.78.189.215:55553
https://200.23.139.211:4443
https://165.253.64.23
https://192.193.104.142
https://192.193.103.42
```

### Additional Details (leave it blank if not applicable)

Shodan query: https://www.shodan.io/search?query=http.favicon.hash%3A%22801517258%22

image

### Additional References

None

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks as always for your contribution @righettod , we appreciate it! :)

**Review by ritikchaddha — APPROVED** [review]

**Comment by kee-reel** [comment]
@righettod first of all - thank you for the contribution!

I've started getting false positives for the template you added :c
The issue is that a lot of APIs respond on a request `GET /modules/ibm_apim/ibm_apim.info.yml` with a JSON like this:
```
{"code":404,"value":"\/modules\/ibm_apim\/ibm_apim.info.yml"}
```
And your template contains matcher that looks for `"modules\\/ibm_apim\\/"`:
```
- 'contains_any(to_lower(body), "ibm developer portal is ready", "package: ibm api developer", "modules\\/ibm_apim\\/")'
```
I can create PR with a fix myself, but I'm not 100% sure that just removing that part with `"modules\\/ibm_apim\\/"` is a good way to go.
How many services are matching with just that part, is it really necessary to look for it?

**Comment by DhiyaneshGeek** [comment]
Hi @kee-reel 

i'm looking into this false positive

thanks for flagging it

**Comment by DhiyaneshGeek** [comment]
Hi @kee-reel 

[10750](https://github.com/projectdiscovery/nuclei-templates/pull/10750) - Fixed FP , can you confirm if these changes works 

Thanks

**Comment by righettod** [comment]
💻Run with the removal of `"modules\\/ibm_apim\\/"` (content of PR #10750):

image

🟠 https://165.253.64.23 not found but it is normal because it is down:

image

🟠 https://192.193.104.142 not found but it is normal because there is a SSL issue:

image

🔴 https://192.193.103.42 not found and this one is up:

image

🤔I see such interesting marker in the code of the page:

image

@kee-reel 
If you made a request to `[BASE]/sites/all/modules/ibm_apim/css/ibm_apim.css` in your context that allowed you to identify the false positive, does the response return something like this:

`{"code":404,"value":"sites\/all\/modules\/ibm_apim\/css\/ibm_apim.css"}`

Thanks in advance 😃

**Comment by kee-reel** [comment]
Hi @righettod ,

Yeah, I found multiple services that return a 404 response containing the path that I've requested (and because these services have nothing in common with IBM, they don't have files you've mentioned).

**Comment by righettod** [comment]
Cool thanks @kee-reel  for the confirmation 👍

**Pull request merged**
