### PR TITLE
Add Another Redirect Payload and Extend the Regex to Recognize it

### PR DESCRIPTION
**Pull request by sbani**
### Template / PR Information

Another vulnerability scanner uses this payload too.

Here's an example:
```
❯ http https://redacted.io/%5C%5Cexample.com/%252e%252e%252f
HTTP/1.1 308 Permanent Redirect
[...]
Location: /\\example.com/%2e%2e%2f/
[...]

<a href="/\\example.com/%2e%2e%2f/">Permanent Redirect</a>.
```

I tested the `Location` header in Chrome and Firefox and both follow the redirect. I also tested the Nuclei template against a vulnerable site.

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)
There will be a CVE too soon(tm)

### CODE REVIEW

**Comment by ehsandeep** [comment]
@sbani thank you for sharing the additional payload, we can still improve the regex to cover and avoid matches on the following cases:

```sh
To Match

location: example.com
location: //example.com
location: http://example.com
Location: https://example.com
Location: https://example.com/
Location: https://example.com/DYNAMIC
location:example.com
Location:http://example.com
Location:https://example.com
Location:https://example.com/
location:https://example.com/DYNAMIC
Location: example.comDYNAMIC
location: http://example.comDYNAMIC
Location: https://example.comDYNAMIC
Location: /\example.com
location: /\example.com/
Location: /\example.com/DYNAMIC
Location: /\\example.com
Location: /\\example.com/
Location: /\\example.com/DYNAMIC

Not To Match

location: /example.com
Location:example.com.DYNAMIC
Location: example.com.DYNAMIC
location: http://example.com.DYNAMIC
Location: https://example.com.DYNAMIC
Location: /\example.com.DYNAMIC
Location: /\\example.com.DYNAMIC
```

@geeknik ^^

**Comment by sbani** [comment]
yeah, I'm not the best with regex but I will try my best.

> @geeknik ^^
this has a meaning?

These kinda make no sense to me:
```
Location: example.comDYNAMIC
location: http://example.comDYNAMIC
Location: https://example.comDYNAMIC
```
Can you please explain those?

Let's say we attack Google.com.

Then these would make sense (because of broken regex on the target):
```
google.com.example.com
example.com/google.com
google.comexample.com
```

**Comment by sbani** [comment]
I think this is it:
```
(?m)^(?:Location\s*?:\s*?)(?:https?:\/\/|\/\/|\/\\\\|\/\\)?(?:[a-zA-Z0-9\-_\.@]*)example\.com\/?(\/|[^.].*)?$
```

https://regex101.com/r/ZDYhFh/1

I also updated my code. But please test it yourself too

**Comment by ehsandeep** [comment]
> These kinda make no sense to me:
> 
> ```
> Location: example.comDYNAMIC
> location: http://example.comDYNAMIC
> Location: https://example.comDYNAMIC
> ```
> 
> Can you please explain those?

@sbani let's consider we are scanning against `target.com` and got the following response

```
Location: example.comtarget.com
location: http://example.comtarget.com
Location: https://example.comtarget.com
```

it's a valid scenario if `comtarget.com` is available to buy.

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
thank you for updating the regex @sbani

**Pull request merged**
