### PR TITLE
AMPPS - Directory Listing Misconfiguration

### PR DESCRIPTION
**Pull request by deFr0ggy**
The issue pertains to server side misconfiguration which allows external parties to access the web server directory listing at different locations. 

The issue is with AMPPS - provided by http://www.softaculous.com/

AMPPS - DIRListing

### CODE REVIEW

**Comment by princechaddha** [comment]
Hello @deFr0ggy, Could you please confirm the changes made?

Also, it is recommended to just add the username in the author field since the stats [here](https://github.com/projectdiscovery/nuclei-templates/blob/master/TEMPLATES-STATS.md) are maintained by author names. 
You can add additional details in the `CONTRIBUTORS.json` file as we close this [PR](https://github.com/projectdiscovery/nuclei-templates/issues/3148). Thank you for contributing to this project 🙌

**Comment by deFr0ggy** [comment]
Hello @princechaddha,

Aligned with your changes made. Really appreciate your time looking into this! You can push these as you feel!

**Comment by deFr0ggy** [comment]
Hello @princechaddha,

Aligned with the changes you've made. You can change the username in the Author Field to (author: deFr0ggy, @github.com/deFr0ggy) as I have one template added on the same name. 

Please feel free to push the templates as per your convenience!

**Review by deFr0ggy — COMMENTED** [review]
Updated the Author Name as suggested by @princechaddha!

**Comment by deFr0ggy** [comment]
I have updated the Author Field of my old Template as well to have consistency for all of my teamplates! 

Thank You @princechaddha :))

**Comment by princechaddha** [comment]
Thank you @deFr0ggy for updating the templates :)

**Pull request merged**
