### PR TITLE
Create wordpress-emails-verification-for-woocommerce.yaml

### PR DESCRIPTION
**Pull request by random-robbie**

### CODE REVIEW

**Comment by bauthard** [comment]
Hey @random-robbie, thank you for adding it, I will update the failed check error.

**Comment by bauthard** [comment]
@random-robbie Can you confirm if the latest changes work on your side and validate the result?

**Comment by random-robbie** [comment]
All good @bauthard

**Comment by bauthard** [comment]
Thank you for confirming @random-robbie

**Pull request merged**
