### PR TITLE
Create spx-default-key.yaml

### PR DESCRIPTION
**Pull request by vagnerd**
### Template / PR Information

* Added SPX PHP Profiler default admin key.

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- https://github.com/NoiseByNorthwest/php-spx

### CODE REVIEW

**Comment by pussycat0x** [comment]
Hi @vagnerd  Can you share a debug data for this template?. we are facing some issues while setting an environment. Thank you for sharing this template 💯

**Comment by vagnerd** [comment]
> Hi @vagnerd Can you share a debug data for this template?. we are facing some issues while setting an environment. Thank you for sharing this template 100

Hi @pussycat0x of course! I used this Dockerfile to set up the environment:

```
FROM php:8.0-apache
WORKDIR /var/www/html

RUN apt update && apt install -y git zlib1g-dev

RUN git clone https://github.com/NoiseByNorthwest/php-spx.git
RUN cd php-spx && git checkout release/latest && phpize && ./configure && make && make install

RUN echo "spx.http_enabled=1" >> /usr/local/etc/php/conf.d/docker-php-spx.ini
RUN echo "spx.http_key=\"dev\"" >> /usr/local/etc/php/conf.d/docker-php-spx.ini
RUN echo "spx.http_ip_whitelist=\"*\"" >> /usr/local/etc/php/conf.d/docker-php-spx.ini
RUN echo "extension=spx.so" >> /usr/local/etc/php/conf.d/docker-php-spx.ini

RUN echo "hello world" > /var/www/html/index.php
RUN echo "<?php phpinfo(); ?>" > /var/www/html/test.php

EXPOSE 80
```
Debug results:
```
$ docker run -it --rm  -v ~/secfx/nuclei-templates:/root/nuclei-templates/ projectdiscovery/nuclei:latest --debug -t default-logins/spx-default-key.yaml -u http://172.17.0.1
...
[INF] [spx-default-key] Dumped HTTP request for http://172.17.0.1/?SPX_KEY=dev&SPX_UI_URI=/

GET /?SPX_KEY=dev&SPX_UI_URI=/ HTTP/1.1
Host: 172.17.0.1
User-Agent: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[DBG] [spx-default-key] Dumped HTTP response http://172.17.0.1/?SPX_KEY=dev&SPX_UI_URI=/
...

[spx-default-key:word-1] [http] [high] http://172.17.0.1/?SPX_KEY=dev&SPX_UI_URI=/ [api_key="dev"]
[spx-default-key:word-2] [http] [high] http://172.17.0.1/?SPX_KEY=dev&SPX_UI_URI=/ [api_key="dev"]
[spx-default-key:status-3] [http] [high] http://172.17.0.1/?SPX_KEY=dev&SPX_UI_URI=/ [api_key="dev"]
```

**Comment by pussycat0x** [comment]
Hi @vagnerd  thanks sharing a data. i have updated the matcher and changed requests -> http. can you check and let me know if it works. 🚀    also please move this template into misconfig directory  and change the file name to `default-spx-key. 


FYI :  We have New protocol syntax update [here](https://github.com/projectdiscovery/nuclei-templates/pull/7041).


```
id: default-spx-key

info:
  name: SPX PHP Profiler - Default Key
  author: vagnerd
  severity: high
  description: |
    SPX PHP profiler default spx key were discovered.
  reference:
    - https://github.com/NoiseByNorthwest/php-spx
  remediation: |
    - https://github.com/NoiseByNorthwest/php-spx#security-concern
  classification:
    cvss-metrics: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:C/C:L/I:L/A:L
    cvss-score: 8.3
    cwe-id: CWE-522
  metadata:
    verified: "true"
  tags: spx-php,debug,misconfig,spx

http:
  - method: GET
    path:
      - "{{BaseURL}}/?SPX_KEY={{api_key}}&SPX_UI_URI=/"

    attack: batteringram
    payloads:
      api_key:
        - dev
        - devel
        - stg
        - stag
        - staging
        - prd
        - prod
        - production
        - test
        - testing
        - spx

    stop-at-first-match: true
    matchers-condition: and
    matchers:
      - type: word
        part: body
        words:
          - "<title>SPX Control Panel</title>"
          - "SPX_ENABLED"
          - "Configuration"
        condition: and

      - type: word
        part: header
        words:
          - "text/html"

      - type: status
        status:
          - 200
   ```

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @vagnerd Thank you so much for sharing this template with the community !

**Pull request merged**
