### PR TITLE
Add detection and default login of Dell Remote Power Management unit.

### PR DESCRIPTION
**Pull request by MegaManSec**
### Template / PR Information

This commit adds detection and default login checks for Dell's rack power distribution units.

- References:

https://dl.dell.com/manuals/all-products/esuprt_ser_stor_net/esuprt_rack_infrastructure/dell-metered-pdu_user%27s%20guide3_en-us.pdf

### Template Validation

I've validated this template locally?
- YES

### CODE REVIEW

**Comment by MegaManSec** [comment]
Also FYI, the response HTTP headers look like this:
```
HTTP/1.0 401 ;unauthorized
Server: UPS_Server/1.0
Content-Type: text/html
Cache-Control: no-cache
Expires: Thu, 26 Oct 1995 00:00:00 GMT
Connection: Close
WWW-Authenticate: Basic realm="DELL_DPI"
```
```
* HTTP 1.0, assume close after body
< HTTP/1.0 200 ;OK
< Server: UPS_Server/1.0
< Content-Type: text/html
< Cache-Control: no-cache
< Expires: Thu, 26 Oct 1995 00:00:00 GMT
< Connection: Close
```

But nuclei cannot handle the response `200 ;OK` since it is not an int.

**Comment by ritikchaddha** [comment]
Hello @MegaManSec, thank you for sharing these templates with us, however, we tried validating these templates but couldn’t find any live host of `Dell Remote Power Management`.
Could you share the debug data with us, it would be of much help.

**Comment by ritikchaddha** [comment]
Thanks for the data, can you share the response to the request after successful login using the default login template?

**Comment by MegaManSec** [comment]
```
# curl 10.1.1.1/index2.html -i -X POST  -u 'admin:nottherealpassword'
HTTP/1.0 401 ;unauthorized
Server: UPS_Server/1.0
Content-Type: text/html
Cache-Control: no-cache
Expires: Thu, 26 Oct 1995 00:00:00 GMT
Connection: Close
WWW-Authenticate: Basic realm="DELL_DPI"

<HTML>
<HEAD>
<TITLE>Unauthorized User</TITLE>
<META http-equiv='Content-Type' content='text/html; charset=iso-8859-1'>
</HEAD>
<BODY>
<CENTER><H1>Unauthorized Access</H1></CENTER>
<BR>
This page of the agent is protected.
Either your Username/Password is invalid, or your access is restricted.
</BODY>
</HTML>
```
and
```
~# curl 10.1.1.1/index2.html -i -X POST  -u 'admin:admin'
HTTP/1.0 200 ;OK
Server: UPS_Server/1.0
Content-Type: text/html
Cache-Control: no-cache
Expires: Thu, 26 Oct 1995 00:00:00 GMT
Connection: Close

<HTML>
<HEAD>
<TITLE>DELL DPI Remote Power Management</TITLE>
<META http-equiv="Content-Type" content="text/html;">


  

<FRAMESET border=0 frameSpacing=0 frameBorder=NO rows=58,* bgcolor="#FFFFFF" title="DELL DPI Remote Power Management">
<FRAME border=0 name="Logo" borderColor=#FFFFFF src="Logo.htm" scrolling=NO frameBorder=0 MARGINWIDTH=0 MARGINHEIGHT=0>
<FRAMESET border=0 frameSpacing=0 frameBorder=NO cols=265,* bgcolor="#FFFFFF" marginwidth="0">
<FRAME border=0 name="Menu" borderColor=#FFFFFF src="menubar.html" frameBorder=0>
<FRAME border=0 name="Content" borderColor=#FFFFFF src="PageStatistics.htm" scrolling=Auto frameBorder=0>
</FRAMESET>
</FRAMESET>
</HEAD>
<NOFRAME>
<BODY BGCOLOR="#FFFFFF">
<CENTER>
<H3>
If browser not support "FRAME", will get this message.
</H3>
</CENTER>
</BODY>
</NOFRAME>
</HTML>

```

**Comment by MegaManSec** [comment]
Can this be merged?

**Review by DhiyaneshGeek — APPROVED** [review]

**Pull request merged**
