### PR TITLE
Keycloak openid config

### PR DESCRIPTION
**Pull request by ehsandeep**
### Template / PR Information

- Added: https://github.com/projectdiscovery/nuclei-templates/issues/1989

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by ehsandeep** [comment]
Hi @rodnt, 

Thank you for sharing this, I've updated the path to default one, can you confirm the changes?

**Comment by rodnt** [comment]
Hi @ehsandeep =)

The default one didn't work.  The image below shows the correct response that works =)
image

**Comment by ehsandeep** [comment]
@rodnt added an additional path, Can you confirm this again?

**Comment by rodnt** [comment]
@ehsandeep It works =) thank you !!

**Pull request merged**
