### PR TITLE
Create put-method-test.yaml

### PR DESCRIPTION
**Pull request by xElkomy**

### CODE REVIEW

**Comment by bauthard** [comment]
Thank you for the PR @xElkomy

**Comment by mzfr** [comment]
@bauthard @xElkomy I wanted to ask in this where does `testing-payload` comes from?

**Comment by xElkomy** [comment]
> @bauthard @xElkomy I wanted to ask in this where does `testing-payload` comes from?

you need to know what the site work on PHP or ASP or node js for you to create a shell and upload it with the put method.

**Comment by mzfr** [comment]
um but like what I wanted to know was how does nuclei get to know what payload to use in it.

**Comment by bauthard** [comment]
@mzfr `testing-payload` is a random string in the post request in 1st request, which later gets checked in the matcher, this template checks and ensure if a web path is writable using the `PUT` method.

**Comment by mzfr** [comment]
@bauthard oh okay so it's nothing specific. I thought there was some pre-defined payload. Thanks

**Comment by bauthard** [comment]
Yes, @mzfr, it's random, you can use any string/data to write.

**Pull request merged**
