### PR TITLE
Adding Jenkins default login

### PR DESCRIPTION
**Pull request by Zandros0**
Hi,

I made a template to verify the default credentials used to connect to the Jenkins dashboard.
An overview of the output results.

asupprimer

### CODE REVIEW

**Comment by ehsandeep** [comment]
@Zandros0 this is really nice, do you have any reference for configuring jenkins with default login setup?

**Comment by geeknik** [comment]
I thought Jenkins [auto-generates](https://www.jenkins.io/doc/book/installing/linux/#unlocking-jenkins) the "default" password for the admin user on a per install basis? During the setup routine the password is dropped into the `$JENKINS_HOME/secrets/initialAdminPassword` file.

**Comment by ehsandeep** [comment]
@geeknik right, so this might come in handy to detect the cases where the user intentionally sets up a weak password.

**Comment by Zandros0** [comment]
> I thought Jenkins [auto-generates](https://www.jenkins.io/doc/book/installing/linux/#unlocking-jenkins) the "default" password for the admin user on a per install basis? During the setup routine the password is dropped into the `$JENKINS_HOME/secrets/initialAdminPassword` file.

Yes you're right, but I found out that some Jenkins are using basic credentials such as admin/admin. So I added the template. Might not really be a "default-credential". 
As there was no template for password checking I thought I might add it just in case some basic credentials are used.

**Comment by geeknik** [comment]
It's a great template, can be adapted to fuzz weak logins. I like fuzzing. 👍🏻

**Comment by Zandros0** [comment]
> I thought Jenkins [auto-generates](https://www.jenkins.io/doc/book/installing/linux/#unlocking-jenkins) the "default" password for the admin user on a per install basis? During the setup routine the password is dropped into the `$JENKINS_HOME/secrets/initialAdminPassword` file.

I found out that in some solutions ([here](https://docs.openshift.com/container-platform/4.7/openshift_images/using_images/images-other-jenkins.html#images-other-jenkins-auth_images-other-jenkins) OpenShift) which is setting Jenkins password as admin/password by default.

**Comment by ehsandeep** [comment]
@Zandros0 this template was failing for Jenkins with enabled CSRF protection, I've updated the template to work.

**Pull request merged**
