### PR TITLE
Add template to detect PLESK instances

### PR DESCRIPTION
**Pull request by righettod**
### Template / PR Information

Hi,

This PR propose a template to detect an instance of the [PLESK](https://www.plesk.com/) products.

- References: https://www.plesk.com/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

image

Source of test taken from [Shodan](https://www.shodan.io/search?query=http.html%3A%22plesk-build%22):

```text
https://81.169.141.202
https://107.152.46.236:8443/
https://64.91.251.34/
https://144.91.98.225:8443/
https://righettod.eu/
```

### Additional Details (leave it blank if not applicable)

Shodan query: https://www.shodan.io/search?query=http.html%3A%22plesk-build%22

image

### Additional References:

None

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @righettod we already have a template for this [http/exposed-panels/plesk-onyx-login.yaml](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/exposed-panels/plesk-onyx-login.yaml)

Let me know if i'm wrong 

Looking forward to hear back from you

Thanks

**Comment by righettod** [comment]
Hi,
I apologize for the duplicate, I will take a look to the template you
mentioned to see if I can add more case or extraction info.
If it is the case I will create a new PR.
You can close this PR.

**Comment by DhiyaneshGeek** [comment]
Hi @righettod thanks for understand 😄

**Comment by righettod** [comment]
@DhiyaneshGeek  I will update existing template because it currently miss some case:

image

**Pull request closed without merging**
