### PR TITLE
Added external-service-interaction Template

### PR DESCRIPTION
**Pull request by andreluna**
### Template / PR Information

- Validation for External Service interaction via Host Header Injection
- References:
    - https://portswigger.net/kb/issues/00300210_external-service-interaction-http
    - https://success.qualys.com/support/s/article/000006843
    - https://owasp.org/www-project-web-security-testing-guide/latest/4-Web_Application_Security_Testing/07-Input_Validation_Testing/17-Testing_for_Host_Header_Injection

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by princechaddha** [comment]
Hello @andreluna, thank you so much for sharing this template with the community and contributing to this project 🍻

We already have a template for this check [here](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/proxy/open-proxy-external.yaml). Let me know if you believe this template is performing a different check. If so, we can proceed with updating the current template with additional request.

You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

**Comment by andreluna** [comment]
> Hello @andreluna, thank you so much for sharing this template with the community and contributing to this project 🍻
> 
> We already have a template for this check [here](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/proxy/open-proxy-external.yaml). Let me know if you believe this template is performing a different check. If so, we can proceed with updating the current template with additional request.
> 
> You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again

Hello @princechaddha . I understand the reference you provided, but the template I sent is directly related to the verification that Qualys performs and not with a proxy in apache2.

See is example:
```
~/templates/ nuclei -id open-proxy-external -u http://catpcha.nsa.gov -silent (no results)
~/templates/ nuclei -t external-service-interaction.yaml -u http://captcha.nsa.gov -silent (results)
[external-service-interaction] [http] [medium] http://captcha.nsa.gov/
```

**Comment by andreluna** [comment]
> > Hello @andreluna, thank you so much for sharing this template with the community and contributing to this project 🍻
> > We already have a template for this check [here](https://github.com/projectdiscovery/nuclei-templates/blob/main/http/misconfiguration/proxy/open-proxy-external.yaml). Let me know if you believe this template is performing a different check. If so, we can proceed with updating the current template with additional request.
> > You can join our [discord server](https://discord.com/invite/projectdiscovery). It's a great place to connect with fellow contributors and stay updated with the latest developments. Thank you once again
> 
> Hello @princechaddha . I understand the reference you provided, but the template I sent is directly related to the verification that Qualys performs and not with a proxy in apache2.
> 
> See is example:
> 
> ```
> ~/templates/ nuclei -id open-proxy-external -u http://catpcha.nsa.gov -silent (no results)
> ~/templates/ nuclei -t external-service-interaction.yaml -u http://captcha.nsa.gov -silent (results)
> [external-service-interaction] [http] [medium] http://captcha.nsa.gov/
> ```

@princechaddha this template be published? What should I do now?

**Comment by princechaddha** [comment]
Hello @andreluna, You are right; both templates check for separate issues. I have changed the severity to "info," as in most cases, this issue can't be escalated, and there would mostly be just DNS interaction. Let me know if you think otherwise.

**Comment by andreluna** [comment]
> Hello @andreluna, You are right; both templates check for separate issues. I have changed the severity to "info," as in most cases, this issue can't be escalated, and there would mostly be just DNS interaction. Let me know if you think otherwise.

Alright, I put it as a medium because Qualys considers it that way. But I agree that it is difficult to escalete.

**Comment by andreluna** [comment]
Hello @princechaddha

Was my template removed from the repository?

**Comment by ritikchaddha** [comment]
Hello there, @andreluna. Yes, your template was removed by this commit [7efb971](https://github.com/projectdiscovery/nuclei-templates/pull/8150/commits/7efb971cbee547d802fa5ee304060a46e254d3db), but we restored it via PR [#8200](https://github.com/projectdiscovery/nuclei-templates/pull/8200).

**Comment by andreluna** [comment]
> Hello there, @andreluna. Yes, your template was removed by this commit [7efb971](https://github.com/projectdiscovery/nuclei-templates/pull/8150/commits/7efb971cbee547d802fa5ee304060a46e254d3db), but we restored it via PR [#8200](https://github.com/projectdiscovery/nuclei-templates/pull/8200).

Okay, very thanks!

**Pull request merged**
