### PR TITLE
Create apollo-default-login.yaml

### PR DESCRIPTION
**Pull request by Paper-Pen**
### Template / PR Information

added Apollo Default Login

- References:

### Template Validation

I've validated this template locally?
- YES
图片

#### Additional Details (leave it blank if not applicable)

https://github.com/apolloconfig/apollo

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by Paper-Pen** [comment]
If the login is successful, the jump will look like this:
图片

If the login fails, this is what will happen after the jump:
图片

**Review by ehsandeep — COMMENTED** [review]
@Paper-Pen thank you for sharing this, the previous version of the template was missing valid matches for some reason, I've updated the matchers + used the request condition to confirm the response of 2nd request.

Can you confirm if the changes look good to you?

**Comment by Paper-Pen** [comment]
> @Paper-Pen thank you for sharing this, the previous version of the template was missing valid matches for some reason, I've updated the matchers + used the request condition to confirm the response of 2nd request.
> 
> Can you confirm if the changes look good to you?

**Comment by Paper-Pen** [comment]
> @Paper-Pen thank you for sharing this, the previous version of the template was missing valid matches for some reason, I've updated the matchers + used the request condition to confirm the response of 2nd request.
> 
> Can you confirm if the changes look good to you?

Yes, thanks for helping to fix it

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
