### PR TITLE
Update Nuclei Detection Templates for National Vulnerability Database Correlation

### PR DESCRIPTION
**Pull request by AdamCrosser**
### Overview

The purpose of this pull request is to update detection templates for common applications to include additional metadata and labeling to make it easier to automatically extract relevant CVEs associated with the version extracted by the template. 

This includes adding metadata tags including the vendor and product name as they are represented within the national vulnerability database.  The previous pull request [Update Confluence Detection Templates With Version Extraction Logic](https://github.com/projectdiscovery/nuclei-templates/pull/7460) provides some additional context on this as well. 

### Template Validation

I've validated this template locally?
- [X ] YES
- [ ] NO

### CODE REVIEW

**Comment by olearycrew** [comment]
Thanks for your contribution @AdamCrosser !

**Comment by ehsandeep** [comment]
@AdamCrosser FYI, We will be setting up automation to populate vendor and product information from CPE to all CVEs templates, let me know if you any feedback or field that we should consider adding that can be obtained automatically.

**Comment by AdamCrosser** [comment]
Thanks @ehsandeep! I can't think of anything at the moment. Would you be okay with merging this PR?

**Comment by ehsandeep** [comment]
@AdamCrosser all the cves are now tagged with a lot of new metadata - https://github.com/projectdiscovery/nuclei-templates/pull/7670

**Pull request merged**
