### PR TITLE
Remove Dell matcher from sonicwall WAF detect (False Positives)

### PR DESCRIPTION
**Pull request by KristinnVikar**
### Template / PR Information

- Fixed false positives generated by the Dell matcher

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

Matching the word `dell` is very prone to false positives.

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by KristinnVikar** [comment]
Playing around with this same template, both `ats` and `teros` have similar false positives.
Should I put additional fixes into the same PR since they're in the same file?

`ats` matches any word that ends with `ats` e.g. St**ats**
`teros` matches anything that starts with `st8` e.g. **ST8**0208

**Comment by GeorginaReeder** [comment]
Thanks so much for your contribution @KristinnVikar , we appreciate it!

**Comment by DhiyaneshGeek** [comment]
Hi @KristinnVikar 

Feel free to put the additional changes in the same PR 

Thanks

**Comment by KristinnVikar** [comment]
> I've pushed the `teros` additional fixes, however I cannot find any information online regarding `ats` being a WAF at all. [Apache Traffic Server](https://en.wikipedia.org/wiki/Apache_Traffic_Server)
> 
> I'm wondering if I should remove `ats` from the template or remove the only the offending pattern

Looking more into it, the recommended WAF for Apache Traffic Server ([see ats repo](https://github.com/apache/trafficserver/tree/master/example/plugins/lua-api/modsecurity)) is ModSecurity, which the template already detects. So my opinion is that we should just remove the `ats` matcher entirely, since it's redundant.

**Comment by pussycat0x** [comment]
Hello @KristinnVikar , thank you so much for sharing this template with the community and contributing to this project :beers:
You can grab some cool PD stickers over here http://nux.gg/stickers :smile:

**Review by pussycat0x — APPROVED** [review]

**Pull request merged**
