### PR TITLE
Update technologies/waf-detect.yaml

### PR DESCRIPTION
**Pull request by Mys7ic**
### Template / PR Information

This commit extends the existing nuclei template for detecting WAFs. The original payload was matched with the reference payloads of the WhatWaf tool and all payloads used by this tool were added to the template. Additionally, a GET request was added, but to prevent a huge load on the tested web service, the option "stop-at-first-match: true" was added. This ensures that only the minimum number of requests are made until a WAF is detected.

As a pentester, I have noticed that the Nuclei template is not always able to detect WAFs, although the template and the tool it is based on are generally good. Therefore, I made these changes to improve the template's detection capability, which already provides me more impact.

## long story short

- add all payloads from Whatwaf (instead of a single one)
- add get request
- set stop-at-first-match

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

In a second point, I would like to initiate a discussion. In my daily work I noticed that often generic WAFs are detected, which often don't have much impact, in this case you wouldn't find an additional waf like modsecurity. To solve this problem, I split the script into "waf-detect.yaml" and "waf-detect-generic.yaml" for myself. The "waf-detect-generic.yaml" file contains only matchers named "apachegeneric", "aspgeneric" and "nginxgeneric", while the corresponding matchers have been removed from "waf-detect.yaml". I welcome discussion of this approach as a suggestion.

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
Hi @Mys7ic Thanks for sharing this template with the community , is there any specific reason to add these additional payloads because the existing payload also triggers the waf and the new payloads which you have added also the same.

is there any specific reason to add additional payloads specific to waf ?

**Comment by Mys7ic** [comment]
hi @DhiyaneshGeek ,
i had added the additional payloads because I regularly received no waf detection via the template during pentests, 
but the tool WhatWaf (which is given as a reference) still finds wafs. of course I can't specify the customer systems here.

I realise that unnecessary load on the targets is to be avoided, so I try to keep this with stop-at-first-match.

In theory, a single payload should be enough to detect a waf, but in practice the wafs seem to react differently to some payloads and sometimes remain undetected.

My basic idea was that if a waf is already detected in a payload, no further requests have to be made and no further load is created. All payloads are executed only, if no waf is detected, then it is also likely that no waf is present. 

I am sure that the pull request should not be accepted without careful consideration and hope for additional input and suggestions for improvements from the community.

**Comment by princechaddha** [comment]
Hey @Mys7ic, many thanks for sharing this template with the community and contributing to the project 🍻.

It's a great addition to our current WAF check, but we aim to keep the request generated by each template as low as possible. Therefore, we have created a separate fuzzing template with a fuzz tag. This means that it won't run in the default scan, but if anyone wants to run an extensive WAF scan, they can manually run it. Please let me know if the made changes look good to you.

**Comment by Mys7ic** [comment]
Hi @princechaddha, i like the solution. this solves both problems (low request count and higher detection capabilities ).

although in the fuzz template, the stop-at-first-match could be removed to detect when multiple WAFs are on a system (e.g. nginxgeneric and additionally cloudflare). but that only makes sense if a unique list of the matching matcher names is output at the end (which, as far as i know, is not possible).

**Comment by princechaddha** [comment]
@Mys7ic Indeed, we can include names in the matcher just as we have done in this template. This will allow the WAF name to be printed upon matching.

```yaml
    matchers:
      - type: regex
        name: instart
        regex:
          - '(?i)instartrequestid'
        part: body

      - type: regex
        name: perimx
        regex:
          - '(?i)access.to.this.page.has.been.denied.because.we.believe.you.are.using.automation.tool'
          - '(?i)http(s)?://(www.)?perimeterx.\w+.whywasiblocked'
          - '(?i)perimeterx'
          - '(?i)(..)?client.perimeterx.*/[a-zA-Z]{8,15}/*.*.js'
        condition: or
        part: response
```

**Pull request merged**
