### PR TITLE
Add versa-default-login template

### PR DESCRIPTION
**Pull request by davidmckennirey**
Good Morning! I have another default credential template to submit. This one is for Versa Networks SD-WAN product, which I have found located at both {{BaseURL}}/versa and {{BaseURL}}/, so I have included both requests in this template. The default credentials are "Administrator:versa123". Getting the matching conditions right was kinda of tricky to prevent FP, but I think this is sufficient. Included is a sample (successful) response for an app at the '/versa' endpoint.

```
HTTP/1.1 302 Found
Server: Apache-Coyote/1.1
X-FRAME-OPTIONS: SAMEORIGIN
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
Strict-Transport-Security: max-age=31536000 ; includeSubDomains
Set-Cookie: JSESSIONID=[REDACTED]; Path=/versa/; Secure; HttpOnly
Location: /versa/
Content-Length: 0
Connection: close
```

### CODE REVIEW

**Comment by ehsandeep** [comment]
Hi @davidmckennirey, 

This one was the complex one as to make the successful detection, you need to make 2 HTTP requests, as it requires CSRF token to log in, a successful detection requires the following steps:-

- 2 HTTP Request
- 2 Dynamic values
- Multi request condition

Completed and updated template which is in a working state, but looks like we identified a bug with **matchers** using along with extractors so keeping this template in a blocked state till we identify the root cause and fix this issue.

**Comment by davidmckennirey** [comment]
Wow! You really did an awesome job taking my template and making it great. I'm gonna study this for the other templates I'm working on. Thanks for the fix 😁

**Comment by ehsandeep** [comment]
Everything should be documented here https://nuclei.projectdiscovery.io/templating-guide/

**Comment by ehsandeep** [comment]
Blocked by https://github.com/projectdiscovery/nuclei/issues/783

**Pull request merged**
