### PR TITLE
Create js-analyse.yaml to analyse js files !

### PR DESCRIPTION
**Pull request by ayadim**
Hi.

I create a template that "Analyse" js files for bug bounty hunters :
- Extract Tokens.
- Extract endpoints.
- Extract URI. (FTP:// , DATA:// , Fille:// ..etc )
- Extract Variables names. (All in one)
here is an image: https://i.imgur.com/l8MFeCP.png
the tested main.js from juicy shop 

Regards

### CODE REVIEW

**Comment by pussycat0x** [comment]
Hi @ayadim Thank you for sharing this template with the community and for your contribution to this project 💯 . I have updated the severity. can you check and let me know if it works  🥂

**Comment by ayadim** [comment]
> Hi @ayadim Thank you for sharing this template with the community and for your contribution to this project 100 . I have updated the severity. can you check and let me know if it works clinking_glasses

yes, it works perfectly and I also remove a comment hope its the last change!  
Thank you for your time.
regards

**Comment by ayadim** [comment]
hi,
can you change the status to done ? or there's something else to add ?

**Comment by DhiyaneshGeek** [comment]
Hi @ayadim we can remove the variable names part, rest all looks good 

Looking forward to hear back from you 😄

**Comment by ayadim** [comment]
> Hi @ayadim we can remove the variable names part, rest all looks good 
> 
> Looking forward to hear back from you 😄 

hi bro.
i see there's some unwanted keywords showing in results but the problem is Go doesn't support lookahead in regex !!

I don't have anything to say 😕 but in js files i love to check variables name it can give you some hints about the web app strucure or it can hold sensitive information. 
You have the right to remove it and i understand the situation, and thank you for responding.

 regards.

**Review by DhiyaneshGeek — APPROVED** [review]

**Comment by DhiyaneshGeek** [comment]
Hi @ayadim Thanks for sharing this template with the community 😄

**Pull request merged**
