### PR TITLE
Changes to reference and description

### PR DESCRIPTION
**Pull request by nrathaus**

### CODE REVIEW

**Comment by ehsandeep** [comment]
@nrathaus looks like we need to escape some chars, also can you have a look at this https://regex101.com/r/B30JFL/1

**Comment by geeknik** [comment]
I believe this regex is more well suited to the task, it will only match on 2.4.20 through 2.4.43 as per the CVE details:

`Apache/2\.4\.([3-3][0-9]|2[0-9]|4[0-3])`

You can test it here: https://regex101.com/r/LI7nvY/1 👍🏻

**Comment by geeknik** [comment]
In order to be compatible with nuclei, we'll have to add extra escaping like so:
`Apache/2\\.4\\.([3-3][0-9]|2[0-9]|4[0-3])`

**Comment by ehsandeep** [comment]
thank you @nrathaus @geeknik for the help.

**Pull request merged**
