### PR TITLE
jboss-default-login.yaml

### PR DESCRIPTION
**Pull request by paradessia**
Adding a template for JBOSS  JMX Console login.

### CODE REVIEW

**Review by toufik-airane — APPROVED** [review]
After further testing, it sounds good. 👍

**Comment by toufik-airane** [comment]
Can we improve the template to add the lack of authentication scenario?
In case you directly connect to an instance that doesn't provide a sign-up page.
cc @ehsandeep

**Comment by paradessia** [comment]
For the second one, we could change the  ```jboss``` with  ```HtmlAdaptor?action=```.

**Review by toufik-airane — APPROVED** [review]
[N/A]

**Review by ehsandeep — APPROVED** [review]

**Pull request merged**
