### PR TITLE
TOP 200 WordPress Plugins Detection

### PR DESCRIPTION
**Pull request by ricardomaia**
### Template / PR Information

This PR introduces 200 Nuclei templates to detect WordPress plugins and extract their versions using informations into readme.txt files.

The standards imposed by WordPress to plugin publication allows some kind of automatization. So I'd created an Python script to scrape the Wordpress website and the SVN repository.

The script source code is avaliable in https://github.com/ricardomaia/nuclei-template-generator-for-wordpress-plugins

In a nutshell the script reads the URL https://wordpress.org/plugins/browse/popular/ until page 10, extract each plugin name and namespace, then in http://plugins.svn.wordpress.org/ website, looks for the "Stable tag" inside the readme.txt for the respective plugin.

The generated template includes tags to top 100 and top 200 plugins by popularity and have an matadata reference to WP-Scan website to list associeted vulnerabilities.

The choice to list only the top 200 plugins was aimed at avoiding excessive requests during the scanning process.

Tested with top 50 WordPress sites listed in https://trends.builtwith.com/websitelist/WordPress

image

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by ricardomaia** [comment]
Perhaps removing the wordpress prefix from the template name is a good idea. So the template name would exactly match the plugin name for inventory purposes.

So instead had something like  `[wordpress-tinymce-advanced:version] [http] [info] https://example.com/wp-content/plugins/tinymce-advanced/readme.txt [5.6.0]` we got just only `[tinymce-advanced:version] [http] [info] https://example.com/wp-content/plugins/tinymce-advanced/readme.txt [5.6.0]`. 

Looks better, doesn't it?

**Comment by ricardomaia** [comment]
To perform the update, I created a GitHub action in my repository that can be incorporated into the Nuclei templates repository as well.

https://github.com/ricardomaia/nuclei-template-generator-for-wordpress-plugins/blob/main/.github/workflows/update-templates.yml

**Comment by princechaddha** [comment]
Hi @ricardomaia,

Thank you for submitting this PR and contributing to this project. We apologize for the delay in responding. Thanks for sharing the `nuclei-template-generator-for-wordpress-plugins` script with the community. We appreciate the effort you put into writing a detailed description of your PR. We do have a template called (https://github.com/projectdiscovery/nuclei-templates/blob/main/fuzzing/wordpress-plugins-detect.yaml)  that can be used to detect WordPress plugins.

The fuzz tag is added to the `wordpress-plugins-detect` template, which means it will not be run during a default scan. This is to prevent excessive traffic per scan.

Can you tell us more about the additional value you see in using separate templates versus a single template with all the paths included? We're always looking for ways to improve and would love to hear your thoughts. Thanks

**Comment by ricardomaia** [comment]
> Hi @ricardomaia,
> 
> Thank you for submitting this PR and contributing to this project. We apologize for the delay in responding. Thanks for sharing the `nuclei-template-generator-for-wordpress-plugins` script with the community. We appreciate the effort you put into writing a detailed description of your PR. We do have a template called (https://github.com/projectdiscovery/nuclei-templates/blob/main/fuzzing/wordpress-plugins-detect.yaml) that can be used to detect WordPress plugins.
> 
> The fuzz tag is added to the `wordpress-plugins-detect` template, which means it will not be run during a default scan. This is to prevent excessive traffic per scan.
> 
> Can you tell us more about the additional value you see in using separate templates versus a single template with all the paths included? We're always looking for ways to improve and would love to hear your thoughts. Thanks

Of course @princechaddha! I've used the fuzzing model a few times and the experience has been frustrating! Resource-intensive to test nearly 90,000 keywords used in the payload.

Furthermore, the models I propose not only identify and detect the version, but also indicate whether it is out of date or not. Note that there is a differentiation in the variable name like `detected_version` and `outdated_version`.

Using the GitHub Actions adds another advantage as it automates the update. The plugin's keyword list hasn't been updated in over 2 years.

image

My proposal, while not covering all possible plugins, is more cost-effective as it focuses on the 200 most popular plugins and is 450 times lighter than the fuzzing approach. Think about applying the [Pareto Principle](https://en.wikipedia.org/wiki/Pareto_principle).

I'm also thinking of expanding the list to the top 1000, allowing users to apply additional filters based on tags like top-200, top-300, top-1000, etc.

**Comment by ricardomaia** [comment]
**Refactoring Done**
- remove unnecessary quotes in the template name field ✅ 
- move templates under "technologies/wordpress/plugins/" directory ✅ 
- move latest version txt file under "helpers/wordpress/plugins/" directory ✅ 
- update payload file path as per new location ✅ 
- update "plugin" tags to "wp-plugin" ✅

**Review by ehsandeep — APPROVED** [review]

**Review by princechaddha — APPROVED** [review]

**Comment by princechaddha** [comment]
Hello @ricardomaia, Thank you for updating the templates and sharing this with the community. Your efforts are greatly appreciated. Cheers!

**Comment by ricardomaia** [comment]
> Hello @ricardomaia, Thank you for updating the templates and sharing this with the community. Your efforts are greatly appreciated. Cheers!

It's a pleasure to contribute to the community! I didn't see the script workflow and deployment to perform updates. Has the upgrade process been implemented differently?

**Pull request merged**
