### PR TITLE
Create ecoa-building-automation-lfd.yaml

### PR DESCRIPTION
**Pull request by Akokonunes**
### Template / PR Information

ECOA Building Automation System Local File Disclosure Vulnerability

Title: ECOA Building Automation System Local File Disclosure Vulnerability
Type: Local/Remote
Impact: Exposure of System Information, Exposure of Sensitive Information
Risk: (4/5)
Release Date: 08.09.2021
Reference : https://www.zeroscience.mk/en/vulnerabilities/ZSL-2021-5679.php

### Template Validation

I've validated this template locally?
- YES

### CODE REVIEW

**Review by Akokonunes — COMMENTED** [review]
Workes, there is a problem on tab character on request. already fixed it

**Comment by Akokonunes** [comment]
@princechaddha thank you my bro, for updating the template.

**Comment by princechaddha** [comment]
hello @Akokonunes, you can close #2663 PR as we are merging the template in this PR.

**Comment by Akokonunes** [comment]
Thank you @princechaddha, Done ! 😎

**Pull request merged**
