### PR TITLE
Create room-alert-detect

### PR DESCRIPTION
**Pull request by gy741**
### Template / PR Information

Hello,

Added AVTECH Room Alert Detection template.

- References: https://avtech.com/articles/166/how-to-access-a-room-alert-monitors-settings-pages-2/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### CODE REVIEW

**Comment by gy741** [comment]
Hello, @tess-ss  @DhiyaneshGeek 

The path seems to be different for each version.

My test case does not have a "gateway" path.

So it doesn't detect the problem.


TEST LOG:
```
root@karas:~# nuclei -t ~/room-alert-detect.yaml -u http://X.X.X.X --debug

GET /gateway HTTP/1.1
Host: X.X.X.X
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/44.0.2403.155 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[INF] [room-alert-detect] Dumped HTTP response for http://X.X.X.X/gateway

HTTP/1.1 404 ERROR
Connection: close

ERROR 404
```
So I checked some exposed versions and used the default path "index.html".

**Comment by tess-ss** [comment]
Hello @gy741 

Thank you for taking time out and contributing to Nuclei :)

In your provided template the decision to create the tech detect was based on the Shodan Query provided by you in the template which is `shodan-query: title:"Room Alert"` also the template name shows the template is for "AVTECH Room Alert Detection" this is why the template was updated in order to detect AVTECH Room Alert cms.

Let me know If you have any questions.

**Comment by gy741** [comment]
Hello, @tess-ss 

Thank you for your quick reply. :)

The first type discovered by shodan is not detected by the changed template. 

image

```
root@karas:~# nuclei -t ~/room-alert-detect.yaml -u http://X.X.X.X --debug

GET /gateway HTTP/1.1
Host: X.X.X.X
User-Agent: Mozilla/5.0 (Windows NT 6.2; WOW64) AppleWebKit/537.36 (KHTML like Gecko) Chrome/44.0.2403.155 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[INF] [room-alert-detect] Dumped HTTP response for http://X.X.X.X/gateway

HTTP/1.1 404 ERROR
Connection: close

ERROR 404
```

However, this site is the room alert site.

image


Detected in the first submitted template "index.html" path.

```
GET /index.html HTTP/1.1
Host: X.X.X.X
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.1 Safari/537.36
Connection: close
Accept: */*
Accept-Language: en
Accept-Encoding: gzip

[INF] [room-alert-detect] Dumped HTTP response for http://X.X.X.X/index.html

HTTP/1.0 200 200
Content-Length: 20556
Connection: close
Content-Type: text/html

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN" "http://www.w3.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
        <head>
                <title>AVTECH Software, Inc. - Room Alert 4E - Advanced IT &amp; Facilities Environment Monitoring, Alerting &amp; More</title>
 ...
        </body>
</html>
[2022-10-04 11:09:10] [room-alert-detect] [http] [info] http://X.X.X.X/index.html
```

**Review by princechaddha — APPROVED** [review]

**Review by princechaddha — APPROVED** [review]

**Comment by princechaddha** [comment]
Hello @gy741, thank you so much for sharing this template with the community and contributing to this project 🍻

**Pull request merged**
