### PR TITLE
Added a google bucket detecter

### PR DESCRIPTION
**Pull request by Thabisocn**
### Template / PR Information

I always manually looked for google storage buckets to see if they have any misconfigurations then thought there must be a way to automate this process of finding google storage buckets in a mobile app's files, so i created a template  .

### Template Validation

I've validated this template locally?
- [* ] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

Screenshot from 2023-09-29 16-14-35

### CODE REVIEW

**Comment by DhiyaneshGeek** [comment]
```
geekfreak@localhost ~ % echo test.txt | nuclei -t test.yaml -vv

                     __     _
   ____  __  _______/ /__  (_)
  / __ \/ / / / ___/ / _ \/ /
 / / / / /_/ / /__/ /  __/ /
/_/ /_/\__,_/\___/_/\___/_/   v3.0.0-dev

		projectdiscovery.io

[INF] Current nuclei version: v3.0.0-dev (development)
[INF] Current nuclei-templates version: v9.6.4 (latest)
[INF] New templates added in latest release: 121
[INF] Templates loaded for current scan: 1
[INF] Targets loaded for current scan: 1
[google-storage-bucket] Google Storage Bucket - Detection (@thabisocn) [info]
[google-storage-bucket] [file] [info] test.txt [chromiumcodereview.appspot.com,codereview.appspot.com]

```

**Comment by pussycat0x** [comment]
Hi @Thabisocn  Thank you for sharing this template with the community and for your contribution to this project. Your efforts are greatly appreciated. Cheers!

**Comment by ritikchaddha** [comment]
Thanks for the contribution @Thabisocn !

We would love to give out our swag for your contribution. Are you on our Discord channel? If not, you can join our [Discord server](https://discord.com/invite/projectdiscovery) and send a note in the `#contributing` channel.

**Comment by Thabisocn** [comment]
It was my pleasure looking forward to creating more with more impact.This
was just the beginning, familiarizing myself with  creating a nuclei
template  .I will send a note on Discord .

**Pull request merged**
