### PR TITLE
Castel Digital Authentication Bypass

### PR DESCRIPTION
**Pull request by Kazgangap**
### Template / PR Information

add Castel Digital Authentication Bypass
https://cxsecurity.com/issue/WLB-2024050032

The sample site for Cxsecurity was not working afterwards, I tested it on other sites.
I have the debug data, but it would not be right to share it directly as it may contain personal information. 
I also tested and scanned through Project Discovery Cloud.

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks as always for your contribution @Kazgangap !

**Comment by DhiyaneshGeek** [comment]
Hi @Kazgangap 

Feel free to join our [Discord server](https://discord.com/invite/projectdiscovery)! Once you're in, just shoot me a DM (geekfreak) so we can discuss together.

**Comment by Kazgangap** [comment]
> Hi @Kazgangap
> 
> Feel free to join our [Discord server](https://discord.com/invite/projectdiscovery)! Once you're in, just shoot me a DM (geekfreak) so we can discuss together.
hi @DhiyaneshGeek 
I messaged you on discord about this.

**Comment by ritikchaddha** [comment]
Hello @Kazgangap, thank you so much for sharing this template with the community and contributing to this project 🍻

**Pull request merged**
