### PR TITLE
add readymade sqli

### PR DESCRIPTION
**Pull request by Kazgangap**
https://packetstormsecurity.com/files/179886/ReadyMade-Unilevel-Ecommerce-MLM-Blind-SQL-Injection-Cross-Site-Scripting.html

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by GeorginaReeder** [comment]
Thanks as always for your contributions @Kazgangap , we appreciate it! :)

**Comment by Kazgangap** [comment]
Any news on the merge?  @ritikchaddha

**Comment by ritikchaddha** [comment]
Hello @Kazgangap,

Apologies for the delayed response. Although we've been trying, we haven't yet been able to validate this template. Your help in sharing the debug data would be much valued.

**Comment by Kazgangap** [comment]
> Hello @Kazgangap,
> 
> Apologies for the delayed response. Although we've been trying, we haven't yet been able to validate this template. Your help in sharing the debug data would be much valued.

From this site you can click on **live preview** and run a demo site.  You can also try the template while the demo site is running. 
That way you can test it there. https://i-netsolution.com/product-details/readymade-unilevel-ecommerce-mlm

`└─$ ./nuclei -u https://******.**********.com/~purposa/demo/ecomm -t /home/kali/Desktop/readymade-sqli.yaml
`

**Comment by ritikchaddha** [comment]
Hey @Kazgangap, I can able to validate the template. Thank you for your help, much appreciated 🍻

**Review by DhiyaneshGeek — APPROVED** [review]

**Pull request merged**
