### PR TITLE
Add detection of Opinio login panel instances

### PR DESCRIPTION
**Pull request by righettod**
### Template / PR Information

Hi,

This PR propose a template to detect instance of the login panel for the **Opinio** software.

- References: https://www.objectplanet.com/opinio/

### Template Validation

I've validated this template locally?
- [x] YES
- [ ] NO

image

Host used for the test found via shodan :

```text
https://18.198.232.99
https://opinio.europarl.europa.eu
https://3.120.64.102
```

### Additional Details (leave it blank if not applicable)

Shodan query:

https://www.shodan.io/search?query=http.title%3A%22Opinio%22

image

### Additional References

None

### CODE REVIEW

**Comment by righettod** [comment]
Hi @DhiyaneshGeek ,

Thanks a lot for the updates 👍 

I will check and provide you a feedback.

Put the PR on hold until I give you my feedback 😉

**Comment by righettod** [comment]
Hi @DhiyaneshGeek 

So, it still correctly identify the instance:

image

image

However, as the redirection is client based and the index page does not contains the version pattern then version is not identified anymore:

image

image

image

I let you decide which version of the template you want to keep 😉

**Comment by ritikchaddha** [comment]
Hello @righettod, thank you for sharing this template. I have updated it to extract the version as well.

**Review by ritikchaddha — APPROVED** [review]

**Comment by righettod** [comment]
> Hello @righettod, thank you for sharing this template. I have updated it to extract the version as well.

Hi @ritikchaddha ,

Thanks a lot 👍

**Pull request merged**
