### PR TITLE
Initialize api templates

### PR DESCRIPTION
**Pull request by zzeitlin**
### Template / PR Information

- Added 63 templates.
- These templates test a provided token against a static API endpoint.

### Template Validation

I've validated this template locally?
- [X] YES
- [ ] NO

#### Additional Details (leave it blank if not applicable)

Note that these templates at `nuclei-templates/ token-spray/*.yaml` are for a different purpose than the ones at `nuclei-templates/exposures/apis/*.yaml`. The latter takes an endpoint and determines if that endpoint exposes a known API. The former takes a provided token and tests it against many API endpoints to determine where the token may be valid.

Many of the templates use a single Matcher, which may be considered weak. This is somewhat mitigated by the fact that these templates point to static API URLs (rather than user-provided URLs) with well-defined APIs.

### Additional References:

- [Nuclei Template Creation Guideline](https://nuclei.projectdiscovery.io/templating-guide/)
- [Nuclei Template Matcher Guideline](https://github.com/projectdiscovery/nuclei-templates/wiki/Unique-Template-Matchers)
- [Nuclei Template Contribution Guideline](https://github.com/projectdiscovery/nuclei-templates/blob/master/.github/CONTRIBUTING.md)
- [PD-Community Discord server](https://discord.gg/projectdiscovery)

### CODE REVIEW

**Comment by ehsandeep** [comment]
Few other points:-

`redirects: false`- redirects are disabled as default, so we can consider removing them.

`User-Agent` To avoid fingerprinting, nuclei uses random UA by default; thus, we can consider removing the hardcoded one if not mandatory.

**Comment by zzeitlin** [comment]
I agree with all of your recommendations. I did not know about CLI variables: using the hard-coded `token.txt` felt clunky and I am glad there is the command line option for variables.
- I removed the superfluous `redirects: false`.
- None of the templates required the use of a `User-Agent` for accurate testing, so I removed those as well.
- I removed `token.txt`.
- I removed the `payloads` section in each `*.yaml` file.

**Comment by ehsandeep** [comment]
Hi @zzeitlin,

What are your thoughts on the directory name in order to keep it distinct for users in line with the use case? here are few options or let me know if you have any other suggestions.

```
key-reuse
key-spray
token-reuse
token-spray
```

**Comment by zzeitlin** [comment]
I like the use of the term `spray` as it is fits what is accomplished by these templates: a single (or few) tokens to be applied against numerous endpoints. I think `token-spray` fits.

**Review by ehsandeep — APPROVED** [review]

**Comment by ehsandeep** [comment]
@zzeitlin this is now added in the latest release of the template project, we are also preparing a quick blog to talk about use- cases.

**Pull request merged**
