### PR TITLE
Create nsicg-default-password 

### PR DESCRIPTION
**Pull request by pikpikcu**
fofa:https://fofa.so/result?qbase64=IHRpdGxlPSLnvZHlurfkupLogZTnvZHmjqfliLbnvZHlhbMi

### CODE REVIEW

**Comment by ehsandeep** [comment]
```
{"agreed":true}
```
is the response for every login request, we need to update the matches for this.

**Comment by dr0pd34d** [comment]
If you do a POST to the following URL:
The response is unique:
/user/login/login

I will update the template and attach it here

**Comment by dr0pd34d** [comment]
A failed login request to that endpoint has the following response:
```html
HTTP/1.1 302 Found
Date: Wed, 13 Jul 2022 01:26:05 GMT
Server: Apache
X-Powered-By: PHP/5.3.3
Set-Cookie: PHPSESSID=8j54ielku5gphfqda495sr41k0; path=/
Location: /user/login/index/logined/fail/username/ns25000/loginnum/2
Content-Length: 0
Connection: close
Content-Type: text/html; charset=UTF-8
```

**Comment by ritikchaddha** [comment]
Hello @pikpikcu thank you so much for sharing this template with the community and contributing to this project 🍻,
Thanks to @dr0pd34d for sharing the additional information, it really helped in validation.

I have updated the template with the appropriate request and matchers.

**Review by princechaddha — APPROVED** [review]

**Pull request merged**
